# Beperkingen van het protocol

In bepaalde omstandigheden, vooral ten gevolge van specifieke weersomstandigheden, kan het protocol niet (volledig) gevolgd worden.
Bij onweer met (kans op-) blikseminslag kan de veiligheid van de staalnemer niet worden gegarandeerd.
Bij vriestemperaturen kan de staalnamelocatie bedekt zijn door een dikke laag ijs, of kan de waterkolom geheel bevroren zijn, zodat het onmogelijk, of niet wenselijk is om een staal te nemen.
Ook als er geen of zeer weinig water boven de waterbodem aanwezig is, is een staalname niet, of niet op de voorgeschreven manier, mogelijk.
Wanneer er geen staal kan genomen worden, wordt dit steeds vermeld op het staalnameformulier in het opmerkingenveld met vermelding van de reden.

Een zeer lage waterstand, makkelijk opwarrelend sediment, een erg dichte watervegetatie (hoge PVI), aanwezigheid van een kroosdek, of drijvende vegetatie die het gehele wateroppervlak bedekt, kan de staalname bemoeilijken en de kwaliteit van het staal beïnvloeden.
Dit dient tevens als opmerking genoteerd te worden op het staalnameformulier.
Intense neerslag kan bij onvoldoende menging de samenstelling nabij het wateroppervlak tijdelijk sterk beïnvloeden.

Wanneer het water doorwaad wordt, kan de waterbodem (met name bij een dikke sliblaag, veendetritus of sapropelium) omgewoeld worden, zodat materiaal in suspensie geraakt in de waterkolom en dit het nemen van een zuiver staal bemoeilijkt, of zelfs onmogelijk maakt.
Dit kan ook het gevolg zijn van recente activiteit van dieren (vissen, watervogels, vee etc.) of menselijke activiteiten zoals scheepvaart en recreatie.
Het is van groot belang om bij tijdelijke verstoring van de waterbodem te wachten tot alle zwevend materiaal terug bezonken is.

De procedure is niet geschikt voor staalname op een bepaalde diepte onder het wateroppervlak, of voor het nemen van een staal dat de volledige waterkolom integreert.

