# Kwaliteitszorg

De kwaliteit van het analyseresultaat wordt in belangrijke mate bepaald door de representativiteit van het staal.
Kwaliteitszorg bij het nemen hiervan is dus een belangrijk gegeven.
Ongebruikte recipiënten dienen steeds gesloten te worden bewaard in een droge en stofvrije ruimte.
Het hergebruik van recipiënten is niet toegestaan omdat residu's van voorgaand gebruik het staal kunnen beïnvloeden.
Onderhoud en het grondig reinigen van het staalnamemateriaal zijn van groot belang in het voorkomen van contaminatie en worden voorzichtig en correct uitgevoerd.
Alleen correct gereinigd materiaal mag getransporteerd en gebruikt worden in het veld.
De handen van de staalnemer moeten proper zijn en er worden latex handschoenen (poederloos) gebruikt.
Bij aanvang van de staalname, dient het materiaal dat in contact komt met het staal grondig gespoeld te worden met water van de staalnamelocatie en in geen geval gereinigd met detergenten etc., omdat deze het staal kunnen contamineren.
Spoelen met lokaal water helpt tevens het materiaal te acclimatiseren aan het staal en beperkt de contaminatie van producten of vorige stalen.
Indien recipiënten werden gecertificeerd als 'contaminant-vrij' is het spoelen van de recipiënten niet noodzakelijk.

Het is van groot belang om bij het waden zeer voorzichtig te werk te gaan om vertroebeling tot een minimum te beperken en eventueel te wachten tot alles terug bezonken is.

De omgevingsfactoren die invloed kunnen hebben op de kwaliteit van het staal (zie 2.3 Beperkingen tot de procedure) worden op het staalnameformulier in het opmerkingenveld ingevuld.
Deze worden in een databank ingevoerd.

Het waterstaal kan veranderingen ondergaan ten gevolge van chemische en biologische processen.
Om dit tegen te gaan is het belangrijk om de hoeveelheid zuurstof in de recipiënten bij de staalname te beperken en de stalen nadien koel en donker te bewaren.
Bij de laboratoriumanalyses van de stalen wordt steeds de zuurtegraad en conductiviteit opnieuw gemeten ter controle en vergeleken met de veldmetingen om eventuele afwijkingen te signaleren.

