# Samenvatting

## Doelstelling

<!-- description: start -->

De **INBO-zoogdierweefselcollectie** bevat diverse type specimens afkomstig van zoogdieren: spierweefsel, vetweefsel, stalen van organen en tanden.
Deze specimens zijn waardevol doordat ze zijn gelinkt aan ecologische autopsie- en/of projectdata.
De specimens worden in collectie gebracht ter (her)gebruik voor verschillende doeleinden waaronder genetisch onderzoek, toxicologische analyses, analyses van ziekten en exacte leeftijdsbepalingen.
Het betreft specimens van zoogdieren zoals carnivoren (oa. das, wolf, wasbeer), knaagdieren (oa. rat, bever) en hoefdieren (oa. ree, damhert, sikahert).

Sommige van de weefsels werden tot op heden in hun geheel ingezameld (bv. complete tong), daar dit tijd uitspaart tijdens het uitvoeren van de autopsies, alsook verzekert dat er voldoende weefsel beschikbaar is voor toekomstige analyses.
De beschikbare opslagcapaciteit zit echter aan zijn limiet.
De algemene doelstelling is om het volume weefsel in langetermijnopslag te verkleinen.

<!-- description: end -->

## Toepassingsgebied

Deze SOP beschrijft hoe een substaal te nemen van dierlijk spierweefsel dat reeds diepgevroren bewaard zit (ca. -20 °C), met als doel het te bewaren om op een later tijdstip DNA te extraheren.

## Niet binnen het toepassingsgebied

Deze SOP beschrijft niet:

-   Hoe de verschillende spierweefsels werden ingezameld.
-   Hoe de uitgevoerde handeling te loggen in een centraal digitaal beheersysteem zoals een collectie management systeem (CMS).
-   De procedure(s) van de DNA-extractie(s).

De handelingen zijn niet (met zekerheid) overdraagbaar op:

-   Andere types ingezamelde weefsels dan spierweefsel.
-   Ingezamelde (spier)weefsels in opslag op afwijkende temperaturen (bijvoorbeeld -80°C of -196°C).

```{=html}
<!--
En waar vinden we deze informatie dan, indien ze beschikbaar is?
-->
```
