# Veiligheid

```{=html}
<!--
Alle aandachtspunten in verband met veilig werken.
-->
```
-   Voor opnames in zeer ondiepe waterlopen (waterdiepte \< 0,5 m) kan alleen op terrein worden gegaan; bij diepere waterlopen (\> 1 m) wordt steeds met 2 personen op terrein gegaan.
    Voor waterlopen met een diepte tussen 0,5 en 1 m hangt het van de veldomstandigheden af of de opname alleen kan geïnventariseerd worden of niet.

-   Indien de opname gebeurt met 2 personen, dient één persoon altijd op de oever te staan; deze persoon kan het veldformulier invullen.

-   Neem steeds een hark of stevige stok mee bij het doorwaden van de waterloop.
    Je kan er de waterdiepte mee peilen voor je in de waterloop gaat; je kan deze gebruiken om gemakkelijker je evenwicht te behouden bij sterke stroming en om je op af te duwen om uit de waterloop te geraken bij steile oevers.

-   De veldmedewerker beschikt steeds over een GSM en een lijst van nuttige telefoonnummers.

-   Tijdens een opname in verontreinigd water draagt men waterdichte handschoenen; na de opname wast men de handen met ontsmettende zeep om het risico op besmetting te beperken.

-   Voorzichtigheid is ten zeerste geboden bij diepe en snelstromende waterlopen, bij weke waterbodem en bij gladde of zeer steile taluds.
    In deze omstandigheden kan een alternatieve opnametechniek toegepast worden (zie \@ref(vegopn)).
    Gebruik een reddingstouw of reddingsvest wanneer de situatie dit vereist.

Tijdens het veldwerk gelden volgende aanvullende veiligheidsregels:

-   algemene veiligheidsregels rond het werken in en nabij water (protocol in ontwikkeling sfp-112);
-   bioveiligheidsmaatregelen voor het voorkomen van de verspreiding van invasieve exoten (protocol in ontwikkeling sfp-015).
