# Referenties {.unnumbered}

Bijkerk R.
(red) (2014).
Handboek Hydrobiologie.Biologisch onderzoek voor de ecologische beoordeling van Nederlandse zoete en brakke oppervlaktewateren.
Deels aangepaste versie (Rapport 2014 - 02).
Stichting Toegepast Onderzoek Waterbeheer, Amersfoort.

DIW (2003).Decreet Integraal Waterbeleid van 18 juli 2003 (B.S. 5/12/2003).
[[https://navigator.emis.vito.be/mijn-navigator?woId=75697]{.underline}](https://navigator.emis.vito.be/mijn-navigator?woId=75697)

Scheers K., Packet J., Denys L., Smekens V., De Saeger S.(2016). BWK en habitatkartering, een praktische handleiding.
Deel 3: handleiding voor het typeren van de stilstaande wateren in Vlaanderen.
Versie 1.
Rapporten Instituut voor Natuur- en Bosonderzoek INBO.R.2016.
11613720

Vanderhaeghe F., Adriaens D., Denys L., Cools N., Jansen I., Herr C., Verstraeten A., Raman M., Wouters J.,Van Calster H. Westra T., Onkelinx T., Van Daele T., Oosterlynck P., Leyssen A., Wackenier M., De Becker P., Piesschaert F., Desmet P., Louette G., Quataert P., Vandenabeele, M.A., Van Elegem B.
(2020).
Ontwikkeling en implementatie meetnetten natuurlijk milieu.
In: Programmatorische aanpak stikstof -- platform passende beoordeling.
Onderzoek, monitoring, methodologie-ontwikkeling en data-ontsluiting door het Instituut voor Natuur- en Bosonderzoek (PAS-PPB periode 2015-2019).
Hoffmann M.
& Gerald Louette G.
(eds.).
Rapporten van het Instituut voor Natuur- en Bosonderzoek (11), Brussel.
blz.
106-116.
