# Onderwerp

## Definities en afkortingen

```{=html}
<!--
Definities van begrippen en afkortingen die noodzakelijk zijn om dit document te begrijpen en het protocol op een gepaste manier te kunnen uitvoeren.
-->
```
**Abundantie of densiteit** = een maat voor de talrijkheid van een soort, meestal gekoppeld aan een bepaalde oppervlakte (densiteit).
Het is het aantal individuen of andere teleenheden (bv. scheuten) van een soort per oppervlakte.
Het gebruik van densiteit als meetvariabele vereist afspraken omtrent de teleenheid (plantenindividu, pollen- en mattenvormers, uitlopers, ...)

**Aquatische vegetatie** = watergebonden vegetatie, drijvend of (gedeeltelijk) ondergedoken in de waterkolom.

**Bedekking** = een maat van voorkomen die meer gelinkt is met biomassa (een soort kan bijvoorbeeld zeer talrijk voorkomen maar met lage biomassa/bedekking): de bedekking van een plantensoort (of laag van de vegetatie, bv. boomlaag) is de proportie van de bodem die bedekt is door een soort, indien alle andere soorten verwijderd zouden worden.
M.a.w. het is de verticale projectie van alle bovengrondse plantendelen van alle individuen van een soort op de bodem.
De bedekking wordt uitgedrukt als een proportie of een percentage.

**Bedekkingsschaal** = een meestal ordinale schaal die gebruikt wordt om in het veld voor een plantensoort de visueel ingeschatte bedekking te noteren.
Sommige schalen zijn een combinatie van klassen voor bedekkingspercentages en klassen voor abundanties bij lage bedekkingen.
Elke klasse in de ordinale schaal krijgt een code die genoteerd wordt.

**Vegetatiegelaagdheid** = verticale organisatie van de vegetatie.
Bij een vegetatie-opname wordt meestal een onderscheid gemaakt in de verschillende structuurlagen (bv. moslaag, kruidlaag, struiklaag en boomlaag).
De kruidlaag omvat alle niet-houtige gewassen en houtige gewassen tot maximaal 80 cm, de struiklaag omvat alle houtige gewassen tussen 80 cm en 6 m.
Lianen worden afhankelijk van hun hoogte tot de kruid-, struik- of boomlaag gerekend.
De boomlaag bestaat uit houtige planten hoger dan 6 m.
Voor bossen ligt de opdeling tussen kruid- en struiklaag op 2 m, voor struik- en boomlaag op 8 m.

**Habitatvlek** = een afgebakende zone waarbinnen een homogeen vegetatietype voorkomt.
De afbakening gebeurt op basis van karteerregels die betrekking hebben op een fytosociologische definitie.
Een synoniem hiervoor is habitatlocatie.

**(Semi-)terrestrische vegetatie** = Niet-aquatische vegetaties (waterplanten - hydrofyten) die aan land gebonden zijn, zij wortelen minstens in de bodem.

**Soortensamenstelling** = de lijst van soorten die voorkomen binnen het proefvlak/onderzochte perceel.

**Strooisellaag** = liggend afgestorven plantenmateriaal bovenop de bodem, niet vasthangend aan de moederplant waarin organisch materiaal nog herkenbaar te vinden is.
Strooisel omvat dus bladeren, stengels, twijgen en andere houtachtige plantenresten, zowel intact en herkenbaar materiaal als gedeeltelijk gecomposteerd en gefragmenteerd materiaal.

**Vegetatie-opname** = beschrijving van de vegetatiesamenstelling door middel van een volledige lijst van de aanwezige soorten en de mate waarin ze voorkomen (biomassa, densiteit, bedekking, ...)

## Doelstelling en toepassingsgebied

```{=html}
<!--
Doelstelling: omschrijving in woorden waarvoor het protocol dient.
Voorbeelden wat er met de gegevens kan gedaan worden.
Probeer de doelstelling zo veel mogelijk generiek te beschrijven en vermijd projectspecifieke doelstellingen.
Toepassingsgebied: bespreek hier onder welke condities het protocol kan gebruikt worden.
-->
```
De beheermonitoringsschaal wordt gebruikt voor het schatten van de mate van voorkomen van plantensoorten over grotere oppervlaktes (grootte-orde van 1000 m² tot enkele hectares), zoals een proefvlakcirkel van 1000 m², delen van gebruikspercelen, beheerblokken en vegetatie-eenheden.
De schaal heeft zowel kenmerken van de klassieke bedekkingsschalen, zoals de schaal van Londo, die gebruikt wordt voor kleine proefvlakken (zie [protocol sfp-401-nl versie 2023.03](../2023.03/index.html)), als van de Tansley-schaal, die ook courant ingezet wordt bij het inventariseren voor grotere oppervlaktes (protocol nog te ontwikkelen).
Net zoals bij een klassieke vegetatie-opname ([protocol sfp-401-nl versie 2023.03](../2023.03/index.html))), gaat het hier om een meer kwantitatief gedefinieerde schaal, echter met minder onderverdelingen als bv.
de Londo-schaal.
In overeenstemming met een klassieke vegetatie-opname ([protocol sfp-401-nl versie 2023.03](../2023.03/index.html))), maar in tegenstelling tot de Tansley-schaal methode, is de beheermonitoringschaal relatief ten opzichte van de oppervlakte waarover men een uitspraak doet.
Vergelijkbaar met de Tansley-schaal methode, heeft de beheermonitoringschaal een aantal aanpassingen waarmee vaak voorkomende problemen bij inschattingen over grotere oppervlaktes kunnen ondervangen worden (bv lokaal afwijkende vegetatie).
Wanneer een grotere oppervlakte (bv. een gebruiksperceel) bekeken wordt, geeft dit een completer beeld van de soortensamenstelling (wat positief is voor de bruikbaarheid van de gegevens op perceelsniveau), maar de inschattingen van de bedekking worden moeilijker waardoor de reproduceerbaarheid lager is.
Enkele voorbeelden van projecten waar deze methode (of een afgeleide vorm ervan) gebruikt is zijn de graslandverificatie in kader van het mestactieplan en de inventarisatie van het historisch permanent grasland in de polders (@DeSaeger2014; @Vriens2010).

