# Onderwerp

## Definities en afkortingen

```{=html}
<!--
Definities van begrippen en afkortingen die noodzakelijk zijn om dit document te begrijpen en het protocol op een gepaste manier te kunnen uitvoeren.
-->
```

**Celkartering**: het ruimtelijk in kaart brengen van het voorkomen van het doeltype binnen een rastercel van 32 m op 32 m

**Doeltype**: het habitat(sub)type of regionaal belangrijke biotoop (rbb) waarvoor de steekproeflocatie is getrokken voor een specifiek meetnet.
Er komt geen overlap voor tussen sub- en hoofdtypes.
De habitat(sub)types en regionaal belangrijke biotopen komen voor terrestrische eenheden in de MNM overeen met de strata.

**GRTS-steekproef**: ruimtelijk gebalanceerde willekeurige steekproef gebaseerd op het GRTS algoritme (Stevens & Olsen, 2004).
Een GRTS-steekproef is gebaseerd op een grid van GRTS-rastercellen met een bepaalde dimensie.
Elke GRTS-rastercel krijgt een uniek GRTS-rangnummer.
Een steekproef met grootte n wordt bekomen door de GRTS-rastercellen met de n laagste rangnummers te selecteren binnen de doelpopulatie.
In de MNM wordt een GRTS-steekproef getrokken voor elk meetnet afzonderlijk.

**MNM**: Meetnetten Natuurlijk Milieu.
Deze meetnetten hebben als doel de toestand en trend van milieudrukken in het natuurlijk milieu op het niveau van Vlaanderen op te volgen ter ondersteuning van het natuurbeleid.
Hiervoor dient de abiotiek in Natura 2000-habitats en regionaal belangrijke biotopen te worden gemonitord.
Eén meetnet volgt één milieudruk op in een specifiek compartiment (grondwater, oppervlaktewater, bodem, inundatiewater of atmosfeer).

**rbb**: regionaal belangrijk biotoop

**steekproefeenheid** of **meetlocatie**: een individueel element van de steekproef en is in toepassing van dit protocol (nl. voor terrestrische types) een rastercel van 32 m op 32 m

## Doelstelling en toepassingsgebied

```{=html}
<!--
Doelstelling: omschrijving in woorden waarvoor het protocol dient.
Voorbeelden wat er met de gegevens kan gedaan worden.
Probeer de doelstelling zo veel mogelijk generiek te beschrijven en vermijd projectspecifieke doelstellingen.
Toepassingsgebied: bespreek hier onder welke condities het protocol kan gebruikt worden.
-->
```

### Doelstelling

Dit protocol beschrijft hoe terrestrische steekproefeenheden ("meetlocaties") worden beoordeeld op de aanwezigheid van het doeltype in een meetnet van de Meetnetten Natuurlijk Milieu (MNM).
De steekproefeenheden zijn het resultaat van een GRTS-trekking voor een specifiek meetnet van de MNM.
Ze worden getrokken uit het meetnetspecifieke steekproefkader, welke de best beschikbare oplijsting vormt van de eenheden die tot de doelpopulatie van het meetnet behoren.
Het steekproefkader van een meetnet is een beperking van het basissteekproefkader van alle meetnetten van de MNM op basis van de lijst types die de doelpopulatie van elk meetnet definiëren.
Het basissteekproefkader is aangemaakt op basis van originele datalagen en datalagen die zijn afgeleid van de Habitatkaart of de Watervlakkenlaag.

De steekproefeenheid van terrestrische habitats is een GRTS-rastercel van 32 m op 32 m waar het doeltype volgens de Habitatkaart voortkomt.
Een polygoon behorend tot een habitat of rbb kan dus meerdere GRTS-rastercellen omvatten.
Een onderscheid wordt gemaakt tussen celmidden- en celgebaseerde types.
Voor de meeste terrestrische types gebeurt de koppeling van GRTS‐rastercellen aan polygonen celcentrumgebaseerd: de GRTS‐rastercel krijgt een habitat- of rbb-type toegekend van een polygoon als het centrum van de rastercel ermee overlapt.
De koppeling van GRTS‐rastercellen aan habitatpolygonen gebeurt evenwel celgebaseerd voor types die vooral voorkomen als kleine of smalle patches of in consequent lage aandelen in het polygoon (nl. de zogenaamde phab‐waarden in de Habitatkaart).
Hierbij krijgt de GRTS‐rastercel een habitattype toegekend van een polygoon als het ermee overlapt.
De celgebaseerde koppeling gebeurt voor habitattypes 1320, 2150, 6210_sk, 6430_bz en 7150 en de rbb‐types brem‐ en gaspeldoornstruweel (rbbsg) en doornstruweel (rbbsp).

De getrokken steekproefeenheden dienen het doeltype te bevatten waarvoor de eenheid is getrokken, voortgaand op de meest recente Habitatkaart, ofwel in het celmidden bij celmiddengebaseerde types of ergens in de cel bij celgebaseerde types.
De aanwezigheid van het doeltype in de rastercel wordt geëvalueerd tijdens het terreinbezoek.
Toch kan het zijn dat in de praktijk de aanwezige vegetatie in de rastercel ter plaatse afwijkt en niet behoort tot het doeltype waarvoor de meetlocatie is getrokken.
Strikt gezien vervalt deze steekproefeenheid en dient de volgende steekproefeenheid te worden bezocht.
Om de kans te vergroten dat de terreinmedewerker een bemonstering kan uitvoeren tijdens het bezoek aan een gebied en de efficiëntie van het terreinwerk niet in het gedrang te brengen:

-   wordt de locatie van de steekproefeenheid voor het terreinbezoek geëvalueerd op basis van een desktop-screening en
-   kan de terreinmedewerker via de procedure in het vervangprotocol binnen een vooraf bepaald gebied een andere steekproefeenheid selecteren die wel geschikt is.

Ten slotte dient in de rastercel van elk geschikte steekproefeenheid een kartering te worden uitgevoerd van het doeltype, verderop de celkartering genoemd.
Met deze informatie zijn veldmedewerkers zonder of met minder vegegtatiekundige expertise in staat de bemonstering of installatie van meettoestellen op een vegetatiekundig geschikte locatie uit te voeren.
Dit kan met tussenkomst zijn van een extra randomisatie in de geschikte zone.

Dit protocol omschrijft de werkwijze van de desktopscreening, de evaluatie van de aanwezigheid van het doeltype, het lokaal vervangen en de celkartering voor terrestrische steekproefeenheden van de MNM.

### Toepassingsgebied

Dit protocol is van toepassing voor de evaluatie, vervanging en celkartering van terrestrische eenheden van GRTS-steekproeven getrokken voor abiotische monitoring in een meetnet van de MNM, met uitzondering van het habitattype 7220.

<!-- description: start -->

<!-- description: end -->
