# Overkoepelende werkwijze met verwijzing naar subprotocols

```{=html}
<!--
Geef hier een overzicht van de stappen van het project protocol.
De verschillende stappen moeten verduidelijkt worden met criteria en richtlijnen wanneer wat moet uitgevoerd worden.
Bijvoorbeeld:
Ga naar de te monitoren locatie.
Volg subprotocol A `<protocol-code>_YYYY.NN` om te bepalen of de locatie tot de doelpopulatie die men wil monitoren behoort (eerste bezoek) of nog steeds behoort (herhaald bezoek).
Volg subprotocol B `<protocol-code>_YYYY.NN` waarin de staalnameprocedure wordt uitgelegd.
Volg subprotocol C `<protocol-code>_YYYY.NN` waarin labo-analyse wordt uitgelegd.

De doelstelling is om de subprotocols te organiseren in een coherent hoofd protocol waarin ontbrekende elementen aangevuld worden die niet in de subprotocols staan, zoals wanneer een bepaald subprotocol wel of niet wordt uitgevoerd, of kleine extra stappen die geen eigen subprotocol vereisen.
-->
```

## Overzicht van de stappen

De steekproef van terrestrische steekproefeenheden, aangeleverd door de meetnetontwerpketen, wordt beschikbaar gesteld via een beveiligde server of andere route.
Via GIS-applicaties (vb. QGIS en QField) worden ze gevisualiseerd aangeboden voor desktopscreening en voor de communicatie van gegevens voor de organisatie op terrein (*outbound*) en de op terrein verzamelde gegegevens (*inbound*).

De evaluatie van een terrestrische steekproefeenheid gebeurt eerst door een desktopscreening (zie \@ref(desktop)):

-   Indien uit de desktopscreening blijkt dat het doeltype van een steekproefeenheid er niet aanwezig kan zijn, dient de steekproefeenheid te worden verwijderd van de steekproef.

-   Indien een steekproefeenheid het doeltype kan bevatten op basis van de visuele controle, wordt het bezocht om ter plekke de beoordelen of het aanwezige type (habitat(sub)type of rbb) overeenkomt met het doeltype waarvoor de steekproefeenheid werd getrokken (zie \@ref(terplekke)).

    -   Als het actuele habitat(sub)type of rbb ter plekke overeenkomt met het beoogde doeltype waarvoor de steekproefeenheid werd getrokken, wordt aansluitend een celkartering uitgevoerd (zie \@ref(celkartering)).

    -   Als het niet overeenkomt met het doeltype, wordt aansluitend gezocht naar een vervanging door een geschikte rastercel in dezelfde polygoon (zie \@ref(lokalevervanging)).

        -   Indien een geschikte rastercel gevonden wordt, zal deze de originele steekproefeenheid vervangen (maar beide grts-adressen worden behouden in de databank). Aansluitend wordt een celkartering uitgevoerd.
        -   Indien geen geschikte rastercel gevonden wordt, is geen lokale vervanging mogelijk en wordt de steekproefeenheid verwijderd van de steekproef.

In de eerste twee stappen wordt beoordeeld of het doeltype kan aanwezig zijn en ter plekke actueel aanwezig is in het celmidden of ergens in de cel van de steekproefeenheid.
Doeltypes die *ergens* in de cel dienen voor te komen, zijn:

-   habitattypes: 1320, 2150, 6210_sk, 6430_bz en 7150
-   rbb‐types: brem‐ en gaspeldoornstruweel (rbbsg) en doornstruweel (rbbsp).

Alle andere terrestrische doeltypes (met uitzondering van habitattype 7220) dienen aanwezig te zijn in het celmidden.
Voor de kalktufbronnen (habitattype 7220) is de populatie‐eenheid de volledige habitatvlek (met variabele, doorgaans beperkte oppervlakte), geïdentificeerd met een punt gekoppeld aan de vlek.
De evaluatie van dit doeltype gebeurt dus niet op niveau van rastercellen maar de hele vlek.

**Let op**: een steekproefeenheid kan voor meer dan één doeltype zijn getrokken, omdat het opgenomen is in meer dan één meetnet en zelfs in hetzelfde meetnet.
Dit laatste is het gevolg van het feit dat een polygoon in de Habitatkaart, waarop de waarden van de rastercellen zijn gebaseerd, meer dan één type (habitat of rbb) kan bevatten, in relatieve verhoudingen zoals weergegeven met de zogenaamde phab-waarden.
In het celmidden kan er echter maar één type voorkomen en dus sluiten types die celmiddengebaseerd zijn elkaar uit.
Wel kan een steekproefeenheid meerdere celgebaseerde types bevatten, al dan niet in combinatie met een celmiddengebaseerd type.
Check dus zeker bij de evaluatie van een terrestrische steekproefeenheid of je deze procedure moet doorlopen voor meer dan één doeltype, dan kan je het werk hiervoor combineren in één procedure.

## Desktopscreening van steekproefeenheden {#desktop}

Om grote, duidelijke fouten in de steekproef op te sporen, dient een steekproefeenheid onderworpen te worden aan een eerste visuele screening.
Hiervoor dient de rastercel van de steekproefeenheid ruimtelijk gevisualiseerd te worden (vb. met QGIS) in combinatie met een aantal GIS-lagen in de meest recente versie, zoals orthofoto's (zomer- en winteropnames), de Habitatkaart, de Watervlakkenlaag en het Digitaal Hoogtemodel Vlaanderen.
Toets visueel af of de rastercel van de steekproefeenheid het doeltype kan bevatten zoals vermeld in databank.
Voorbeelden van fouten die hiermee kunnen worden opgespoord zijn: recent verdwenen habitat door ruimtebeslag, recent gewijzigd habitat door beheer, open doelhabitat gelegen in boshabitat of omgekeerd en rastercellen van celmiddengebaseerde types die slechts in een klein hoekpunt overlappen met een polygoon van het doelhabitat.
Duid aan in de databank met steekproefeenheden of de steekproefeenheid volgens deze screening wel of niet tot het doeltype kan behoren.
Het resultaat van de screening wordt gebruikt om de steekproef bij te werken: indien de steekproefeenheid **overduidelijk** niet tot het doeltype kan behoren, wordt het verwijderd uit de steekproef.
Indien er geen duidelijke visuele aanwijzingen zijn dat het doeltype er niet kan aanwezig zijn, wordt de steekproefeenheid in een volgende stap beoordeeld op de aanwezigheid van het doeltype ter plekke.

## Beoordeling op aanwezigheid van het doeltype ter plekke {#terplekke}

**1. Bereid het bezoek aan de steekproefeenheid voor**

Controleer in de GIS-applicatie wie de eigenaar en/of beheerder is van het gebied waarin de steekproefeenheid gelegen is.
Toets af bij de meetnetverantwoordelijke of projectcoördinator of vergunningen noodzakelijk zijn en je bezoek is gemeld bij de eigenaar en/of beheerder.
Toegankelijkheid van militaire gebieden dient een week voor het terreinbezoek aangevraagd te worden via mail aan het betreffende kwartier, met de boswachter in cc.
Zij laten weten op welke dagen en tussen welke uren je het terrein mag betreden.
Bij het betreden en het verlaten van het terrein op de dag zelf dien je telkens telefonisch contact op te nemen met de kwartiercommandant.

**2. Evalueer de timing van je bezoek**

Evalueer of je geplande bezoek gebeurt in de (sub)optimale periode voor kartering van het doeltype.

<!-- nog tabel invoegen met optimale periode -->

**3. Bezoek de steekproefeenheid en navigeer naar het celmidden**

Met de hulp van de GPS-ontvanger op je tablet of smartphone navigeer je naar de locatie van de te beoordelen steekproefeenheid.
Eens je je in de nabijheid van de meetlocatie bevindt (vb. op 10 m), navigeer je met behulp van de RTK-GPS-ontvanger naar de exacte locatie van het centrum van de steekproefeenheid.

**Let op**: in de rastercel kan een permanent kwadrant van het meetnet biotische habitatkwaliteit aanwezig zijn.
Het is 3 m op 3 m groot en bevindt zich ten noordwesten van het celmidden: het celmidden van de rastercel is het zuidoostelijk hoekpunt van het permanent kwadrant.
Vermijd zo veel mogelijk dit kwadrant om vertrappeling van de vegetatie te voorkomen.
Dit kan eenvoudig door het celmidden te benaderen vanuit het zuidoosten, indien het terrein dit toelaat.

**4. Evalueer de toegankelijkheid**

Is het terrein waar de steekproefeenheid gelegen is ontoegankelijk, duid dit aan in de GIS-applicatie en vermeld de reden en de vermoedelijke duur van ontoegankelijkheid.
Mogelijke redenen zijn: overstroming, afsluiting, broedseizoen, beheerwerken, enz.
Is het terrein wel toegankelijk, dan evalueer je de aanwezigheid van het doeltype in de rastercel.

**5. Evalueer of het doeltype aanwezig is**

De GIS-applicatie geeft aan welk doeltype op een steekproefeenheid aanwezig zou moeten zijn en indien van toepassing de laatste keer dat het type werd bepaald in het veld.
De wijze waarop het wordt geëvalueerd is afhankelijk van het doeltype:

-   voor de evaluatie van de aanwezigheid van habitat(sub)types 1320, 2150, 6210_sk, 6430_bz en 7150 en de rbb‐types brem‐ en gaspeldoornstruweel (rbbsg) en doornstruweel (rbbsp) is het voldoende dat het doeltype ergens in de 32 m x 32 m rastercel aanwezig is.
-   voor alle andere terrestrische types (behalve 7220) dient het doeltype aanwezig te zijn in het midden van de rastercel.

De bepaling van het aanwezige habitat(sub)type of rbb gebeurt met behulp van de [veldsleutels](https://www.vlaanderen.be/inbo/de-biologische-waarderingskaart/bwk-handleiding-veldsleutels/).

Duid aan in de GIS-applicatie of het aanwezige habitat(sub)type of rbb overeen komt met het doeltype, in de cel of in het celcentrum.
Komt het overeen, dan is de steekproeflocatie geschikt; bevestig het doeltype in de GIS-applicatie en voer aansluitend een celkartering en markering uit (zie \@ref(celkartering)).
Komt het niet overeen, dan is de steekproeflocatie niet geschikt: geef in de GIS-applicatie aan dat de steekproefeenheid het doeltype niet bevat en

-   bevat het een ander type: geef aan welk type het bevat
-   is het geen habitat of rbb meer: geef de reden op, indien je dit kan inschatten.

Start aansluitend met de lokale vervangprocedure (zie \@ref(lokalevervanging).

## Celkartering en markering van geschikte steekproefeenheden {#celkartering}

Blijkt, na het doorlopen van bovenstaande stappen, dat de steekproefeenheid **het doeltype bevat**, dan voer je aansluitend een celkartering en markering uit.
De celkartering houdt in dat je ter plaatse beoordeelt waar het doeltype actueel aanwezig is in de 32 m op 32 m rastercel.

**1.Plaats een markering**

Plaats met behulp van de hamer een metalen buisanker (van 30 of 50 cm lengte, afhankelijk van het type ondergrond) in de grond op de plaats van het celmidden.
Zorg ervoor dat de bovenkant van het anker nog zichtbaar is en maak hieraan het plastic meetmerk vast.
Dit doe je door het meetmerk op de opening van het anker te plaatsen en de plug door het gat van het meetmerk in het buisanker te slaan.
Hierdoor knelt het meetmerk vast in het buisanker.
Controleer of het anker vast zit in de grond: als je het gemakkelijk kan uittrekken, plaats dan een langer buisanker.
Staat er hoge, dichte vegetatie waardoor je het meetmerk moeilijk zou terugvinden (vb. bramenstruweel, riet), plaats een bamboestok met gekleurde top naast het meetmerk.

**2. Oriënteer jezelf en de rastercel op het terrein**

Oriënteer jezelf op het terrein met behulp van de locatie van het celmidden, de visuele voorstelling van de rastercel en de Habitatkaart in de GIS-applicatie.
Je kan ook navigeren naar (één van) de vier hoekpunten van de rastercel om het gebied binnen de rastercel af te bakenen.
Dit kan ook letterlijk met behulp van bamboestokken.

**3. Beoordeel het gebied binnen de rastercel**

Doorloop de rastercel (vermijd de zone van het permanent kwadrant) of loop aan de rand van de rastercel voor zover de gevoeligheid van de vegetatie dit toelaat.
Vermijd onnodige verplaatsingen om vertrappeling van de vegetatie te minimaliseren.
Teken in de GIS-applicatie waar in de rastercel het doeltype actueel aanwezig is.
Specifiek voor de steekproefeenheden van het grondwatermeetnet: duid aan of en waar de rastercel wordt doorsneden door een beek of gracht.

## Lokale vervanging van niet-geschikte steekproefeenheden {#lokalevervanging}

Blijkt, na het doorlopen van bovenstaande stappen, dat de steekproefeenheid **het doeltype niet bevat**, dan doorloop je aansluitend de procedure voor het vinden van een vervangcel.
Je gaat hierbij in (een deel van) de polygoon waarin de niet-geschikte rastercel gelegen is, op zoek naar een rastercel dat wel het doeltype bevat.
Volg hiervoor het protocol [sfp-001-nl 2023.01](https://inbo.github.io/protocols/2023.01/index.html).
In de GIS-applicatie vind je voor elke te evalueren steekproefeenheid een lijst van mogelijke vervangrastercellen die je volgens een vooraf vastgelegde volgorde evalueert zoals beschreven in protocol [sfp-001-nl 2023.01](https://inbo.github.io/protocols/2023.01/index.html).
De mogelijke vervangrastercellen worden gevisualiseerd in de GIS-applicatie wanneer je hebt aangeduid dat de oorspronkelijke rastercel het doeltype niet bevat.

<!-- Nog te specifiëren: In het geval van grote polygonen kan het aflopen en evalueren van de mogelijke vervangrastercellen zeer veel moeite en tijd in beslag nemen. Om dit te beperken, worden grote polygonen (gelijk aan of meer dan...?) opgedeeld volgens de met de polygoon overlappende GRTS-level03-cellen van 128 m op 128 m. Enkel die GRTS-level03-cel waarin de originele steekproefeenheid gelegen is, wordt verder beschouwd. Dit ruimtelijke beperking van mogelijke vervangcellen bij grote polygonen is reeds doorgevoerd in de lijst van mogelijke vervangcellen in de GIS-applicatie. -->

Noteer na het doorlopen van het vervangprotocol of een lokale vervanging mogelijk is, en indien dit zo is, welke rastercel uiteindelijk deze vervanging doet.
Werd een lokale vervanging gevonden, voer dan de celkartering en markering uit zoals hiervoor beschreven in \@ref(celkartering).
