# Extra aspecten van veiligheid t.o.v. de subprotocols

```{=html}
<!--
Geen herhaling van wat al in subprotocols staat
-->
```

Voorzie en draag voor het terreinwerk aangepaste kledij (vb. (lies)laarzen) en persoonlijke beschermingsmiddelen (vb.tekenwerende broek en hemd, zonnecrème, pet).
Tekenbeten meld je volgens de INBO-procedure.
Merk je dat een eigenaar duidelijk geen ongewenst bezoek wil (vb. heel terrein afgerasterd, camerabewaking, waarschuwingsborden met bedreigende taal, agressief blaffende honden), betreed dan het terrein niet.
Is het terein ontoegankelijk door overstroming, dan kan het moeilijk zijn om het terrein goed in te schatten.
Ook in dat geval betreed je best het terrein niet.
Voel je je niet veilig, verlaat de locatie.

Toegankelijkheid van militaire gebieden dient een week voor het terreinbezoek aangevraagd te worden via mail aan het betreffende kwartier, met de boswachter in cc.
Zij laten weten op welke dagen en tussen welke uren je het terrein mag betreden.
Bij het betreden en het verlaten van het terrein op de dag zelf dien je telkens telefonisch contact op te nemen met de kwartiercommandant.

Meld problemen in verband met veiligheid op terrein bij de meetnetbeheerder, projectcoördinator en de preventie-adviseur.
