# Benodigdheden

## Apparatuur

-   hand-GPS (nauwkeurigheid +/- 5 m)

-   (eventueel) RTK -- GPS (nauwkeurigheid ongeveer 5 cm)

-   (eventueel) kompas

-   (eventueel) digitale camera

-   (eventueel) tablet of veldcomputer

-   (eventueel) Fieldmap configuratie (GPS, digitaal kompas, veldcomputer)

-   reservebatterijen

## Materiaal

-   wegenatlas, kaartmateriaal op voorhand voorbereid via GIS

-   notaboek of --fiches (zie Bijlage 2 Veldformulier)

-   voldoende schrijfmateriaal

-   flora (naamgeving volgens Flora van België het Groothertogdom Luxemburg,
    > Noord Frankrijk en de aangrenzende gebieden (Lambinon *et al.*, 1998))

-   loep (8x, 10x, 15x)

-   lint- (min. 5m) of vouwmeter

-   4 markeerstokken + touw (met markering proefvlaklengte en -diagonaal)

-   eventueel markeerverf voor in bossystemen

-   recipiënten (mapjes, krantenpapier, plastic zakje) om niet gedetermineerde
    > planten te bewaren

-   paraplu (om papieren droog te houden)

-   (eventueel) materiaal voor permanente markering (bv. Fenopaal)

