# Extra aspecten van kwaliteitszorg t.o.v. de subprotocols

```{=html}
<!--
Geen herhaling van wat al in subprotocols staat
-->
```
Enkele tips bij het maken van een vegetatie-opname:

-   Vertrappel de vegetatie in de plot zo min mogelijk vooraleer je een vrij volledige soortenlijst hebt en de bedekkingen hebt ingeschat. Doe hierna nog een check op soorten die je eventueel miste meer centraal in de plot of vanop de knieën.
-   Maak eerst een lijst van de aanwezige soorten, schat pas bedekkingen als je lijst min of meer volledig is.
-   Als je na 5 minuten geen nieuwe soort meer vindt, dan wordt de opname stopgezet.
-   Tracht de meest bedekkende soorten bovenaan te groeperen in je lijst.
-   In een 3 m x 3 m plot is een 30 cm x 30 cm vlakje daarbinnen gelijk aan 1%. Een band van 30 cm op een 3 m is dan gelijk aan 10%.
-   De totale som van alle bedekkingen in éénzelfde vegetatielaag kan meer dan 100% zijn door overlap, maar kan ook erg laag zijn, bijvoorbeeld 10% in buntgrasvegetatie op stuifduin.
-   De totale som van kruidlaag, open bodem, strooisellaag en (korst)moslaag is minimaal 100%.
-   Kiemplanten van bomen en struiken duid je aan met een "(k)" na de soortnaam.
-   Soorten net buiten opnamevlak kunnen vermeld worden, maar dit moet je duidelijk weergeven door de naam te laten volgen door "(R)".

