---
title: "Vinknip van vissen nemen en bewaren"
author:
  - name:
      given: "Charlotte"
      family: "Van Driessche"
    email: "charlotte.vandriessche@inbo.be"
    orcid: "0000-0003-1606-8758"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
    corresponding: true
  - name:
      given: "David"
      family: "Halfmaerten"
    email: "david.halfmaerten@inbo.be"
    orcid: "0000-0001-5105-6328"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Rein"
      family: "Brys"
    email: "rein.brys@inbo.be"
    orcid: "0000-0002-0688-3268"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
reviewer:
  - name:
      given: "Jeroen"
      family: "Van Wichelen"
    email: "jeroen.vanwichelen@inbo.be"
    orcid: "0000-0002-0255-9591"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Io"
      family: "Deflem"
    email: "io.deflem@inbo.be"
    orcid: "0000-0002-9302-5367"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Rhea"
      family: "Maesele"
    email: "rhea.maesele@inbo.be"
    orcid: "0009-0009-6756-797X"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
file_manager:
  - name:
      given: "Charlotte"
      family: "Van Driessche"
    email: "charlotte.vandriessche@inbo.be"
    orcid: "0000-0003-1606-8758"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
keywords: ['vinknip','weefselstaalname','DNA-barcoding','vissen','genetische staalname','veldprotocol']
language: nl
lang: nl-BE
date: "`r Sys.Date()`"
protocol_code: sfp-101-nl
version_number: "2026.02"
template_name: sfp
theme: water
community: "inbo"
publisher: Instituut voor Natuur- en Bosonderzoek (INBO)
rightsholder:
  - name:
      given: Instituut voor Natuur- en Bosonderzoek (INBO)
    email: info@inbo.be
    ror: 00j54wy13
funder:
  - name:
      given: Instituut voor Natuur- en Bosonderzoek (INBO)
    email: info@inbo.be
    ror: 00j54wy13
site: bookdown::bookdown_site
bibliography: referenties.yaml
link-citations: TRUE
license: CC-BY 4.0
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
---

```{=html}
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titels staan en vermeld expliciet "niet van toepassing".
-->
```
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
library(pander)
panderOptions("table.alignment.default", "left")
metadata <- rmarkdown::metadata
path_to_protocol <- get_path_to_protocol(metadata$protocol_code)
type <- get_protocol_type(metadata$protocol_code, auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
revs <- map_chr(
  metadata[["reviewer"]],
  \(x) x$name |> paste(collapse = " ")
)
fms <-  map_chr(
  metadata[["file_manager"]],
  \(x) x$name |> paste(collapse = " ")
)
tibble(
  reviewers = paste(revs, collapse = ", "),
  documentbeheerder = fms,
  protocolcode = metadata[["protocol_code"]],
  versienummer = metadata[["version_number"]],
  taal = metadata[["language"]],
  thema = metadata[["theme"]]
) %>%
  pander::pander(split.tables = Inf)
rm(revs, fms)
```

```{r results="asis"}
sprintf("Controleer [deze tabel](../%s.html){target=\"_blank\"} om te zien of een meer recente versie beschikbaar is.", type) |> cat() # nolint
```
