# Extra aspecten van veiligheid t.o.v. de subprotocols

Tijdens het veldwerk gelden volgende veiligheidsregels:

-   Algemene veiligheidsregels rond het werken in en nabij water ([sfp-112] Nog te ontwikkelen).

-   Bioveiligheidsmaatregelen voor het voorkomen van de verspreiding van invasieve exoten ([sfp-015] Nog te ontwikkelen).

-   Veiligheidsvoorschriften van de deelprotocols ([sfp-114-nl 2024.03](../2024.03/index.html), [sfp-115-nl 2024.04](../2024.04/index.html)).

Voorzichtigheid is ten zeerste geboden bij diepe en snelstromende waterlopen, bij weke waterbodem en bij gladde taluds.
In deze omstandigheden kan een alternatieve monsternametechniek toegepast worden (zie Werkwijze - Bemonstering waterkolom en vullen van de recipiënten).
Gebruik een veiligheidsstouw of reddingsvest wanneer de situatie dit vereist.

Neem steeds een hark of stevige stok mee als steun bij het doorwaden van de waterloop.
Je kan er de waterdiepte mee peilen voor je in de waterloop gaat; je kan deze gebruiken om je evenwicht te behouden.
Bovendien kan het een hulp zijn om een steile oever te beklimmen.

Tijdens een staalname in water draagt men waterdichte handschoenen; na de opname wast men de handen met ontsmettende, fosfaatvrije zeep om het risico op besmetting te beperken.

De staalnemer beschikt steeds over een GSM en een lijst van nuttige telefoonnummers.
