---
title: Abiotische staalname waterlopen
author:
- name: Leyssen, An
  orcid: 0000-0003-3537-286X
date: '`r Sys.Date()`'
reviewers: Kevin Scheers, Jo Packet, Luc Denys, Geert De Knijf, Vincent Smeekens,
  Toon Westra
file_manager: Toon Westra
protocol_code: spp-117-nl
version_number: '2024.06'
language: nl
lang: nl
template_name: spp
project_name: mnm
site: bookdown::bookdown_site
bibliography: referenties.yaml
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
url: https://inbo.github.io/protocols/
github_repo: inbo/protocolsource
params:
  dependencies:
    value:
    - protocol_code: sfp-113-nl
      version_number: '2023.04'
      params: .na
      appendix: false
    - protocol_code: sfp-114-nl
      version_number: '2024.03'
      params: .na
      appendix: false
    - protocol_code: sfp-115-nl
      version_number: '2024.04'
      params: .na
      appendix: false
---

```{=html}
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titel hoofdingen staan en vermeld expliciet "niet van toepassing".
-->
```
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
library(pander)
panderOptions("table.alignment.default", "left")
metadata <- rmarkdown::metadata
path_to_protocol <- get_path_to_protocol(metadata$protocol_code)
type <- get_protocol_type(metadata$protocol_code, auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
tibble(
  reviewers = metadata[["reviewers"]] |> paste(collapse = ", "),
  documentbeheerder = metadata[["file_manager"]],
  protocolcode = metadata[["protocol_code"]],
  versienummer = metadata[["version_number"]],
  taal = metadata[["language"]],
  projectnaam = metadata[["project_name"]]
) %>%
  kable()
```

```{r results="asis"}
sprintf("Controleer [deze tabel](../%s.html){target=\"_blank\"} om te zien of een meer recente versie beschikbaar is.", type) |> cat() # nolint
```
