# WIJZIGINGEN VORIGE VERSIES

Dit is de eerste revisie van het document. De tekst is gebaseerd op bestaande documenten in het INBO, literatuurgegevens en gesteund op de kennis van de terreinmedewerkers van het INBO.

2.  # ONDERWERP

    1.  ## Definities en afkortingen

-   **Peil:** De gemeten waarde van de top van de peilbuis naar het wateroppervlak in de peilbuis. Soms wordt dit ook herleidt t.o.v. het maaiveld (m-mv), maar binnen het INBO is de afspraak dat het peil t.o.v. de top van de peilbuis genoteerd wordt.

-   **Stijghoogte / drukhoogte:** Het potentieel peil van het wateroppervlak van grondwater, gemeten vanaf een bepaald niveau (bv. Tweede Algemene Waterpassing, TAW). Doorgaans wordt de bodem van de peilbuis gebruikt.

-   **TAW:** Tweede Algemene Waterpassing. Referentiehoogte waar alle hoogtemetingen in België tegenover gebruikt worden. Het gemiddeld zeeniveau bij laagwater te Oostende wordt gebruikt als nulpeil.

    1.  ## Doelstelling en toepassingsgebied

Deze richtlijn heeft betrekking op peilmetingen in een peilbuis, geplaatst volgens het protocol beschreven in de richtlijn SVP-104 (richtlijnen voor het plaatsen van een peilbuis)..

Het doel van de metingen (manueel of met automatische drukmeters) is op langere termijn een tijdreeks van de grondwaterstand te verkrijgen.

De richtlijn gaat niet in op de meetfrequentie en de vereiste lengte van meetreeksen. Dit is afhankelijk van de doelstellingen van het meetnet en de vereiste betrouwbaarheid.

Als algemene regel kan wel worden gesteld dat éénmaal per maand meten een absoluut minimum is en dat bij voorkeur met vaste meetintervallen wordt gemeten.

## Beperkingen tot de procedure (indien van toepassing)

De tekst gaat niet in op andere methodes om het peil te meten zoals akoestische metingen of drukmetingen in gesloten peilbuizen. Voor metingen in sterk zilte of sterk verontreinigde omstandigheden en grondwater in diepe en afgesloten watervoerende lagen zijn correcties en extra voorzorgsmaatregelen vereist die hier niet worden besproken.

