---
title: Veldmeting abiotiek oppervlaktewater met behulp van WTW Multi 3430 veldmeter
author:
- name: Scheers, Kevin
  orcid: 0000-0002-4756-4247
date: '2021-02-17'
reviewers: An Leyssen, Luc Denys, Geert De Knijf, Toon Westra
file_manager: Toon Westra
protocol_code: sfp-115-nl
version_number: '2024.04'
language: nl
lang: nl
template_name: sfp
theme: water
site: bookdown::bookdown_site
bibliography: referenties.yaml
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
url: https://inbo.github.io/protocols/
github_repo: inbo/protocolsource
---

# Metadata {.unnumbered}

Placeholder

<!--chapter:end:index.Rmd-->

# Wijzigingen t.o.v. vorige versies

## [2024.04](../2024.04/index.html)

-   Dit is de eerste versie van het protocol

```{=html}
<!--
Omschrijf hier welke wijzigingen er gebeurd zijn ten opzichte van de vorige versie. 
Vermeld bij elk versienummer, de reden van de wijziging en - wanneer relevant - een beknopte beschrijving van de wijziging.
Gesorteerd van recent naar oud. 

## [2020.02](../2020.02/index.html)

- Toevoeging van ontbrekende stap in het stappenplan
- Verbetering van schrijffouten

## [2020.01](../2020.01/index.html)

- Eerste versie van het protocol
-->
```
<!--chapter:end:NEWS.md-->

# Afhankelijkheden

Placeholder

<!--chapter:end:01_afhankelijkheden.Rmd-->

# Onderwerp

## Definities en afkortingen

**Oppervlaktewater:** al het permanent of op geregelde tijdstippen stilstaande of stromende water op het landoppervlak, aan de landzijde van de basislijn vanaf waar de breedte van de territoriale zee wordt gemeten (DIW 2003).

**Staalnamelocatie** of **steekproefeenheid:** het waterlichaam (poel, vijver, ...) waarvan de abiotische karakterisatie wordt beoogd en waarbinnen het staalnamepunt zich bevind.
Voor stilstaande wateren is dit het gehele waterlichaam, voor waterlopen is dit een 100 meter segment van de waterloop (dit segment wordt aangeduid als het meest stroomafwaarts gelegen punt van het te bemonsteren 100 meter segment).

**Staalnamepunt:** de exacte plaats binnen de staalnamelocatie waarop de abiotische staalname wordt uitgevoerd.

**UPW**: ultrapuur water is sterk gezuiverd water dat vrijwel volledig vrij is van o.a.
carbonaat, magnesium- en calciumionen, organische verbindingen en gassen; het heeft een elektrische geleidbaarheid van ongeveer 0,055 µS/cm bij 25 °C.

**Waterkolom:** de diepte van het water van de waterspiegel (het wateroppervlak) tot de onderwaterbodem.

## Doelstelling en toepassingsgebied

Deze procedure beschrijft de bepaling van een selectie fysisch-chemische variabelen op een mengstaal van de waterkolom (genomen volgens SVP-114) op een specifieke plaats en tijdstip in het veld met behulp van de digitale veldmeter WTW Multi 3430.
De hiermee gemeten variabelen zijn: de elektrische conductiviteit (EC) of het elektrisch geleidend vermogen (EGV), af te lezen in µS/cm bij lage waarden of mS/cm bij hoge waarden, de saliniteit (g/kg), de concentratie opgeloste zuurstof (mg/l), de zuurstofverzadiging (%), de zuurtegraad (pH) en temperatuur (°C).
De variabelen opgeloste zuurstof, zuurstofverzadiging en temperatuur zijn zeer beïnvloedbaar door manipulatie en transport en moeten daarom altijd in het veld worden gemeten (deze worden door het analytisch labo niet opnieuw gemeten).
Bij verdere analyse van het mengstaal zal de conductiviteit (EC) en zuurtegraad (pH) ook in het labo worden bepaald als controletest om de stabiliteit van de chemische toestand van het staal gedurende transport en bewaring te verifiëren.
De daarbij bekomen waarden kunnen afwijken van de bepalingen in het veld.

Deze gestandaardiseerde procedure kan toegepast worden op mengstalen van alle typen stilstaande en stromende oppervlaktewateren.
Dit protocol is specifiek ontworpen voor de monitoring in kader van de meetnetten natuurlijk milieu (Vanderhaeghe et al. 2020).

<!--chapter:end:02_onderwerp.Rmd-->

# Beperkingen van het protocol

Er zijn geen beperkingen tot deze procedure anders dan de beperkingen die het nemen van een mengstaal (zie protocol bemonstering waterkolom oppervlaktewater SVP-114[ ]()), waarop deze veldmeting gebeurt, onmogelijk maken.

<!--chapter:end:03_beperkingen.Rmd-->

# Principe

Bepaling van de fysisch-chemische toestand van oppervlaktewater in het veld aan de hand van een selectie gemeten variabelen op basis van een mengstaal met behulp van de digitale veldmeter WTW Multi 3430.

<!--chapter:end:04_principe.Rmd-->

# Vereiste competenties

-   Nemen van een mengstaal (SVP-114)

-   Bediening veldmeter type WTW Multi 3430 (SIP-055B)

<!--chapter:end:05_competenties.Rmd-->

# Benodigdheden

Placeholder

## Apparatuur

### Digitale veldmeter type WTW Multi 3430

### Geleidbaarheidselektrode, type WTW IDS TetraCon 925

### Zuurstofelektrode, type WTW IDS FDO925

### Zuurtegraadelektrode, type WTW IDS Sentix 940

## Materiaal

### Staalname-emmer:

### Maatbeker:

### Staalnameformulier (analoog of digitaal)

## Reagentia en oplossingen (indien van toepassing) {#reagentia}

<!--chapter:end:06_benodigdheden.Rmd-->

# Werkwijze

Placeholder

## Uitvoering

## Registratie en bewaring van resultaten

<!--chapter:end:07_werkwijze.Rmd-->

# Kwaliteitszorg

Zorg er steeds voor dat het toestel correct wordt gekalibreerd bij de start van een meting.
Houd het toestel, de elektroden en de bijhorende koffer proper en droog.
Buffers voor controle en kalibratie dienen, indien niet voor eenmalig gebruik, regelmatig te worden aangevuld en vervangen zodat deze niet verdund of gecontamineerd worden.
Voor verdere informatie over het gebruik, kalibratie en onderhoud van dit toestel verwijzen we naar het protocol SIP-055B.

Onderhoud en het grondig reinigen van het staalnamemateriaal zijn van groot belang voor het voorkomen van contaminatie en dienen voorzichtig en correct te gebeuren.
Alleen correct gereinigd materiaal mag getransporteerd en gebruikt worden in het veld.
Handen van de staalnemer moeten proper zijn en bij voorkeur worden latex handschoenen (poederloos) gebruikt.
Handen worden best gespoeld met water van de staalnamelocatie en in geen geval met detergenten etc., omdat deze het staal kunnen contamineren.
Bij aanvang van de staalname, dient het materiaal dat in contact komt met het staal gespoeld te worden met water van de staalnamelocatie.
Spoelen met lokaal water helpt het materiaal te acclimatiseren aan het staal en beperkt de contaminatie van producten of vorige stalen.

Om contaminatie te voorkomen wordt het substaal waarop de bepalingen werden uitgevoerd niet gebruikt voor andere doeleinden.

De gemeten waarden dienen steeds zorgvuldig en leesbaar ingevuld te worden op het staalnameformulier en dit formulier moet op zijn beurt correct worden geklasseerd.
Indien van toepassing dienen eventuele omgevingsfactoren die invloed kunnen hebben op de kwaliteit van het staal op het staalnameformulier worden ingevuld (indien analoog, met potlood of watervaste stift) in het opmerkingenveld en achteraf in een databank worden bewaard zodat deze later kunnen worden geraadpleegd.

<!--chapter:end:08_kwaliteitszorg.Rmd-->

# Veiligheid

Om mogelijke besmetting en verwondingen bij de staalnemer, en mogelijke contaminatie van het staal te voorkomen, worden tijdens de staalname van het waterstaal waterbestendige, poederloze handschoenen gedragen.

Alle algemene veiligheidsregels in verband met werken in en langs water of werken vanuit een boot zijn van toepassing (zie protocol Veiligheid in en rond water [SVP-112]()).

Ook bioveiligheidsmaatregelen in verband met verspreiding van invasieve niet-inheemse soorten en pathogenen zijn van toepassing (zie protocol Bioveiligheidsmaatregelen [SVP-015]()).

<!--chapter:end:09_veiligheid.Rmd-->

# Samenvatting

Niet van toepassing

<!--chapter:end:10_samenvatting.Rmd-->

# Referenties {.unnumbered}

DIW (2003).
Decreet Integraal Waterbeleid van 18 juli 2003 (B.S. 5/12/2003).
[[https://navigator.emis.vito.be/mijn-navigator?woId=75697]{.underline}](https://navigator.emis.vito.be/mijn-navigator?woId=75697)

<!--chapter:end:11_referenties.Rmd-->

# (APPENDIX) Bijlagen {.unnumbered}

<!--chapter:end:12_appendices.Rmd-->

```{r, results="asis"}
if (exists("params")) {
  if (!is.null(params$dependencies)) {
    mdfiles <- paste0(map_chr(params$dependencies, "protocol_code"),
                      "-",
                      map_chr(params$dependencies, "version_number"),
                      ".md")
    child_docs <- file.path(map_chr(params$dependencies, "version_number"),
                            mdfiles)

    child_docs <- child_docs[map_lgl(params$dependencies, "appendix")]

    if (length(child_docs) > 0) {
      res <- map(child_docs, knit_child, quiet = TRUE)
      cat(
        c("# (PART) Subprotocols {.unnumbered}", "", unlist(res)), sep = "\n")
    }
  }
}
```

<!--chapter:end:13_subprotocols.Rmd-->

