# Veiligheid

-   In urbane gebieden dient de projectleider voorafgaand het plaatsen van de peibuizen een controle uit te voeren op het [klip portaal](https://klip.vlaanderen.be/).
    Indien op de locatie aanduidingen zijn van FLUXYS leidingen of FARYS (oranje palen) mogen de werken niet uitgevoerd worden en moet er teruggekoppeld worden met de projectleider.

    https://media.licdn.com/dms/image/v2/D4E12AQHf56e2AcH0Dg/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1667812041241?e=2147483647&v=beta&t=nAkv4KBMwCAdZVOjNPLZ8bEfayNUez-NBKCjcp-pGuA

-   Houd bij het boren de rug recht en knieën gebogen.
    Plaats tijdig een verlengstuk zodat je niet moet bukken bij het boren en het terug omhoog trekken van de boor.

-   Wees voorzichtig tijdens onweer in het open veld.
    De metalen staaf kan bliksem aantrekken.

-   Houd de guts vast bij de synthetische handvaten.
    Deze zorgen voor isolatie indien je een ondergrondse elektriciteitskabel zou raken.

-   Houd bij het omhoog trekken van de pulsboor nooit de pulsboor vlak boven het scharnierpunt vast.

-   Verplaats de klem voor de verbuizing tijdig bij het omhoog trekken van de verbuizing zodat je niet moet bukken.
    Schroef ook tijdig een verlengstuk van de verbuizing af zodat je minder gewicht omhoog moet trekken.

