# Onderwerp

## Definities en afkortingen

<!--
Definities van begrippen en afkortingen die noodzakelijk zijn om dit document te begrijpen en het veldprotocol op een gepaste manier te kunnen uitvoeren.  
-->

*Definities nog toe te voegen*

+ GRTS

+ GRTS-steekproef

+ Steekproefeenheid

+ GRTS-rastercel

+ Type

+ Doeltype

## Doelstelling en toepassingsgebied

<!--
Doelstelling: omschrijving in woorden waarvoor het veldprotocol dient. Voorbeelden wat er met de gegevens kan gedaan worden. Probeer de doelstelling zo veel mogelijk generiek te beschrijven en vermijd projectspecifieke doelstellingen.
Toepassingsgebied: bespreek hier onder welke condities het veldprotocol kan gebruikt worden.
-->

Wanneer je een steekproefeenheid van een bepaald meetnet bezoekt op het terrein en de steekproefeenheid blijkt niet geschikt voor bemonstering, kan je via de vervangingsprocedure binnen een vooraf bepaald gebied een andere steekproefeenheid selecteren dat wel geschikt is. Dit vergroot de kans dat je tijdens een terreinbezoek in een gebied een bemonstering kan uitvoeren. Het is echter niet gegarandeerd dat in het gebied via de vervangsprocedure een geschikte steekproefeenheid wordt gevonden.

De beoordeling of een steekproefeenheid geschikt is voor bemonstering hangt af van meetnet tot meetnet en moet gespecificeerd worden in een projectprotocol. In de meeste gevallen wordt een steekproefeenheid als geschikt beoordeeld als het doeltype (of één van meerdere doeltypes) aanwezig is in de centoïde van de steekproefeenheid.   

Deze vervangingsprocedure kan enkel toegepast worden bij een GRTS-steekproef waarbij de steekproefeenheid een GRTS-rastercel (van bijvoorbeeld 32m x 32m) is. Dit is het geval voor de meeste terrestrische habitattypen en regionaal belangrijke biotopen (rbb).