# Veiligheid

```{=html}
<!--
Alle aandachtspunten in verband met veilig werken.
-->
```

-   Voor opnames in ondiepe wateren (waterdiepte \< 1 m) kan alleen op terrein worden gegaan; bij diepere wateren (\> 2 m) wordt steeds met 2 personen op het terrein gegaan.
    Voor wateren met een diepte tussen 1 en 2 m hangt het van de veldomstandigheden af of het veldwerk alleen kan uitgevoerd worden of niet.

-   Neem steeds een hark of stevige stok mee bij het waden.
    Je kan er de waterdiepte mee peilen voor je in het water gaat; je kan deze gebruiken om je evenwicht te behouden of als hulpstuk gebruiken om uit het water te geraken bij steile oevers.

-   De veldmedewerker beschikt steeds over een GSM en een lijst van nuttige telefoonnummers.

-   Tijdens een opname in verontreinigd water draagt men waterdichte handschoenen; na de opname wast men de handen met ontsmettende zeep om het risico op besmetting te beperken.

-   Voorzichtigheid is ten zeerste geboden bij diepe wateren, bij weke waterbodem en bij gladde of zeer steile taluds.
    In deze omstandigheden kan een alternatieve opnametechniek toegepast (zie [vegetatieopname](#vegetatieopname)) vegetatieopname – waterdiepte bepaalt de wijze van opname).
    Gebruik een reddingstouw of reddingsvest wanneer de situatie dit vereist.

-   Bij bootwerk wordt er minstens met twee personen geïnventariseerd die voldoende ervaring hebben om de boot en uitrusting te bedienen.
    De boot, reddingsvesten en roeispanen zijn in goede staat en indien nodig gekeurd volgens de vereiste voorschriften.
    Bij uitval van de motor of in geval van nood kan de boot bediend worden door roeispanen (min. 2 stuks).

Tijdens het veldwerk gelden volgende aanvullende veiligheidsregels:

-   Algemene veiligheidsregels rond het werken in en nabij water (protocol in ontwikkeling sfp-112).

-   Bioveiligheidsmaatregelen voor het voorkomen van de verspreiding van invasieve exoten (protocol in ontwikkeling sfp-015).
