# (APPENDIX) Bijlagen {.unnumbered}

## Bijlage 1: Determinatiewerken {#bijlage1}

### Algemene flora's

-   Duistermaat L. (2020) Heukels’ Flora van Nederland. (24ste editie) Naturalis/Noordhoff ISBN 978-90-01-58956-1

-   Eggelte H. (2000) Veldgids Nederlandse Flora. KNNV. ISBN 90 5011 135 1.

-   Verloove, Filip & Van Rossum, Fabienne. (2023). Flora van België, het Groothertogdom Luxemburg, Noord-Frankrijk en de aangrenzende gebieden (Pteridofyten en Spermatofyten) (fourth Dutch edition, 2023). Agentschap Plantentuin Meise.

-   Rich T.C.G. & Jermy A.C. (1998) Plant Crib. Botanic Society of British Isles. ISBN 0 901158 28 3.

-   Rothmaler, W. (1994) Exkursionsflora von Deutschland, Gefässpflanzen: Atlasband 3. Gustav Fischer. ISBN 3-334-60829-8.

-   Schou J.C., Moeslund B., van de Weyer K., Lansdown R.V., Wiegleb G., Holm P., Baastrup-Spohr L. & K. Sand-Jensen (2023) Aquatic Plants of Northern and Central Europe including Britain and Ireland. WILDGuides ISBN 9780691251011

### Geïllustreerde flora's

-   Blaymey M., Grey-Wilson C. (1989) Geïllustreerde Flora . Thieme. ISBN 90 5210 059 4.

-   Weeda & Westra (1994) De Nederlansde oecologische flora 1-5. KNNV. ISBN 90 5011 129 7.

### Atlas

-   Van Landuyt W. et al. (2006) Atlas van de Flora van Vlaanderen en het Brusselse Gewest. Nationale plantentuin van België. ISBN90 726 1968 4.

### Herkenning van water- en/of oeverplanten

-   Haslam et al. (1987) British Water Plants. FSC Publications. ISBN 1 85153 107 3.

-   Hoogers et al. (1983) Herkenning van de voornaamste water- en oeverplanten in vegetatieve toestand. Pudoc, Wageningen. ISBN 90 220 0833 9.

-   Meriaux et al. (s.d.) Guide pratique de détermination des plantes aquatiques à l’état vegetatif du bassin Artois-Picardie. Agence de l’eau.

-   Orton et al. (2000) zoekkaart algemeen voorkomende waterplanten. AMINAL.

-   Preston C.D. (2001) Aquatic plants in Britain and Ireland. BSBI. ISBN 0 946589 69 0.

-   Roelf Pot (2002) Veldgids Water- en oeverplanten. KNNV. ISBN90 5011 151 3.

-   van de Wijer, Schmidt, Kreimeier, Wassong (2018) Fachbeiträge des LfU Heft Nr. 119. Bestimmungsschlüssel für die aquatischen Makrophyten (Gefässpflanzen, Armleuchteralgen und Moose) in Deutschland. Ministerium für Ländliche Entwicklung, Umwelt und Landwirtschaft des Landes Brandenburg.

### Gerichte determinatiewerken

-   Aichele & Schwegler (2002) Grassengids. Tirion. ISBN 90-5210-467-0.

-   Bruinsma et al. (2018) Determinatietabel van kranswieren van de Benelux. Stichting Jeugdbondsuitgeverij. ISBN 978 90 5107 060 6.

-   Fitter et al. (1984) Grasses, sedges, rushes and ferns of Britain and Northern Europe. Collings. ISBN 0 670 80688 9.

-   Hermans et al. (1988) Zeggen van Limburg. KNNV. ISBN 90 5011 020 7.

-   Hubbard (1992) Grasses. Penguin. ISBN 0-14-013227-9.

-   Krause W. (1997) Susswasserflora van Mitteleuropa, 18 Charales (Charophyceae). Gustav Fischer. ISBN 3-437-25056-6.

-   Lansdown, R.V. (2008) Water Starworts: Callitriche of Europe. BSBI. ISBN 978 09 011 583 69.

-   Maier E.X., Bruinsma J. et al. (1998) Handboek Kranswieren. Charaboek Hilversum.

-   Moore (2005) Charophytes of Great-Britain and Ireland. BSBI. ISBN090115816X.

-   Muller et al. (2006) Plantes invasives en France . Museum Histoire Naturelle. ISBN 2856535704.

-   Philips et al. (1980) Grassen, varens, mossen en korstmossen. Centraal Boekhuis. ISBN 90-274-4579-6.

-   Preston C.D. (1995) Pondweeds of Great Britain and Ireland. BSBI. ISBN 0 901158 24 0.

-   Schotsman D.H. (1967) Les Callitriches. Lechevalier.

-   Urbaniak J., Gabka M. (2014) Polish charophytes. An illustrated guide to identification.. Wydawnictwo Uniwersytetu Przyrodniczego we Wrocławiu. ISBN 978-83-7717-166-0.

-   van der Ploeg (1990) De Nederlandse breedbladige fonteinkruiden. KNNV. ISBN 90 5011 036 3.

-   van Wijk (1986) De smalbladige fonteinkruidsoorten in Nederland, herkenning en oecologie. KNNV.

-   Schubert H., Blindow I., Nat E., Korsch H., Gregor T., Denys L., Stewart N., van de Weyer K., Romanov R., Casanova M.T. (2024). Charophytes of Europe. ISBN : 978-3-031-31897-9.

### Artikels

-   Denys L., Packet J., Van Landuyt W. (2004) Neofyten in het Vlaamse water: signalement van vaste waarden en rijzende sterren. Natuur.focus.

-   Van Landuyt W. (2007) Herkenning van de vier in België voorkomende drijvende Lemna-soorten. Dumortiera.

## Bijlage 2: Veldformulier habitattype 2190_a {#bijlage2}

[PDF Veldformulier habitattype 2190_a](./media/N2000-VeldprotocolLSVI_2190a.pdf)

## Bijlage 3: Veldformulier habitattype 3110 {#bijlage3}

[PDF Veldformulier habitattype 3110](./media/N2000-VeldprotocolLSVI_3110.pdf)

## Bijlage 4: Veldformulier habitattype 3130_aom {#bijlage4}

[PDF Veldformulier habitattype 3130_aom](./media/N2000-VeldprotocolLSVI_3130aom.pdf)

## Bijlage 5: Veldformulier habitattype 3130_na {#bijlage5}

[PDF Veldformulier habitattype 3130_na](./media/N2000-VeldprotocolLSVI_3130na.pdf)

## Bijlage 6: Veldformulier habitattype 3140 {#bijlage6}

[PDF Veldformulier habitattype 3140](./media/N2000-VeldprotocolLSVI_3140.pdf)

## Bijlage 7: Veldformulier habitattype 3150 {#bijlage7}

[PDF Veldformulier habitattype 3150](./media/N2000-VeldprotocolLSVI_3150.pdf)

## Bijlage 8: Veldformulier habitattype 3160 {#bijlage8}

[PDF Veldformulier habitattype 3160](./media/N2000-VeldprotocolLSVI_3160.pdf)
