---
title: Veldprotocol LSVI stilstaande wateren
subtitle: 
author:
- name:
    given: An
    family: Leyssen
  email: an.leyssen@inbo.be
  orcid: 0000-0003-3537-286X
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
  corresponding: true
- name:
    given: Jo
    family: Packet
  email: jo.packet@inbo.be
  orcid: 0000-0001-5590-323X
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
- name:
    given: Kevin
    family: Scheers
  email: kevin.scheers@inbo.be
  orcid: 0000-0002-4756-4247
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
- name:
    given: Vincent
    family: Smeekens
  email: vincent.smeekens@inbo.be
  orcid: 0000-0003-2996-2716
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
- name:
    given: Florian
    family: Van Hecke
  email: florian.vanhecke@inbo.be
  orcid: 0009-0004-3499-2279
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
reviewer:
- name:
    given: Toon
    family: Westra
  email: toon.westra@inbo.be
  orcid: 0000-0003-2478-9459
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
file_manager:
- name:
    given: Toon
    family: Westra
  email: toon.westra@inbo.be
  orcid: 0000-0003-2478-9459
  affiliation: Instituut voor Natuur- en Bosonderzoek (INBO)
keywords: LSVI; vegetatieopname; stilstaande wateren; 31xx; 2190; veldprotocol; 3110;
  3130; 3130aom; 3130na; 3140; 3150; 3160
language: nl
date: '`r Sys.Date()`'
protocol_code: sfp-408-nl
version_number: '2025.03'
template_name: sfp
theme: vegetation
community: inbo
publisher: Instituut voor Natuur- en Bosonderzoek (INBO)
site: bookdown::bookdown_site
bibliography: referenties.yaml
link-citations: true
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
params:
  dependencies:
    value:
    - protocol_code: sfp-113-nl
      version_number: '2023.04'
      params: .na
      appendix: false
---

```{=html}
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titels staan en vermeld expliciet "niet van toepassing".
-->
```

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
library(pander)
panderOptions("table.alignment.default", "left")
metadata <- rmarkdown::metadata
path_to_protocol <- get_path_to_protocol(metadata$protocol_code)
type <- get_protocol_type(metadata$protocol_code, auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
revs <- map_chr(
  metadata[["reviewer"]],
  \(x) x$name |> paste(collapse = " ")
)
fms <-  map_chr(
  metadata[["file_manager"]],
  \(x) x$name |> paste(collapse = " ")
)
tibble(
  reviewers = revs,
  documentbeheerder = fms,
  protocolcode = metadata[["protocol_code"]],
  versienummer = metadata[["version_number"]],
  taal = metadata[["language"]],
  thema = metadata[["theme"]]
) %>%
  pander::pander(split.tables = Inf)
rm(revs, fms)
```

```{r results="asis"}
sprintf("Controleer [deze tabel](../%s.html){target=\"_blank\"} om te zien of een meer recente versie beschikbaar is.", type) |> cat() # nolint
```

