# Onderwerp

## Definities en afkortingen

**Avimap:** Avimap is een digitale tool ontwikkeld door SOVON voor het uitvoeren van territoriumkartering van broedvogels in het veld.

**code repository**: Een code repository is een digitale opslagplaats waar de broncode van softwareprojecten wordt beheerd en opgeslagen, vaak met versiebeheer om wijzigingen bij te houden.
Het stelt ontwikkelaars in staat om samen te werken, wijzigingen te volgen en terug te keren naar eerdere versies van de code.

**CRS:** Een CRS, of Coordinate Reference System, is een systeem dat wordt gebruikt om geografische locaties op de aarde te definiëren.
Een CRS beschrijft hoe tweedimensionale of driedimensionale ruimtelijke gegevens worden gepositioneerd, en hoe ze worden geprojecteerd op een plat vlak.
Amersfoort/RD New (EPSG:28992) is een voorbeeld van een lokale CRS, specifiek voor Nederland, dat gebruikmaakt van een projectie die is geoptimaliseerd voor het Nederlandse grondgebied.

**MAS:** Het MAS, of Meetnet Agrarische Soorten, monitort broedvogels (en zoogdieren) in agrarische gebieden om trends in aantallen en verspreiding vast te stellen, en de effectiviteit van beschermingsmaatregelen te evalueren [@MAS].
Dit meetnet reeds toegepast in Nederland en met de opstart van het MBAG project ook in Vlaanderen.

**MBAG:** Het MBAG project, of Meetnet Biodiversiteit in het Agrarisch Gebied, is een initiatief van het Instituut voor Natuur- en Bosonderzoek (INBO) in Vlaanderen dat gericht is op het monitoren en analyseren van de biodiversiteit in landbouwgebieden.
Het project richt zich op het verkrijgen van inzicht in de biodiversiteit, met een focus op akkervogels, bestuivers, bodembiodiversiteit, en landschapselementen, om zo bij te dragen aan zowel natuurbehoud als duurzame landbouwpraktijken [@MBAG].

**QGIS:** QGIS is een open-source geografisch informatiesysteem waarin je geografische gegevens importeren, bekijken, bewerken, analyseren en visualiseren [@QGISSoftware].

**Query:** Een query is een verzoek om informatie uit een database of dataset te verkrijgen.
Het is een gestructureerde manier om gegevens op te vragen, te filteren, te bewerken, of te manipuleren

**Sovon:** Sovon, voluit Sovon Vogelonderzoek Nederland, coördineert landelijke vogelmonitoring en -onderzoek, met als doel de aantallen en verspreiding van vogels in Nederland te bepalen, de trends te verklaren, en de resultaten beschikbaar te maken voor natuurbeleid, beheer, en maatschappelijke doeleinden.

**WFS:** Een WFS, of Web Feature Service, is een webstandaard om geografische data via het internet op te vragen en te manipuleren.

```{=html}
<!--
Definities van begrippen en afkortingen die noodzakelijk zijn om dit document te begrijpen en het protocol op een gepaste manier te kunnen uitvoeren.
-->
```
## Doelstelling en toepassingsgebied

**Doelstelling**

Deze procedure beschrijft het stappenplan om MAS data te downloaden via de WFS-server van Sovon en deze data te exporteren voor verdere analyse.
Dit wordt uitgevoerd via een specifieke workflow in QGIS.

**Toepassingsgebied**

De procedure kan toegepast worden door mensen die een account aanmaken en rechten aanvragen bij Sovon.

```{=html}
<!--
Doelstelling: omschrijving in woorden waarvoor het protocol dient.
Voorbeelden wat er met de gegevens kan gedaan worden.
Probeer de doelstelling zo veel mogelijk generiek te beschrijven en vermijd projectspecifieke doelstellingen.
Toepassingsgebied: bespreek hier onder welke condities het protocol kan gebruikt worden.
-->
```

