# Overkoepelende werkwijze met verwijzing naar subprotocols

## Downloaden van de data van de Sovon WFS-server

De MAS-data worden geïmporteerd van de Sovon WFS-server via QGIS [@QGISSoftware].

1.  Een account aanmaken via <https://www.vogelatlas.be/user/newuser>

    1.  Rechten aanvragen via Sovon voor gebruik van de WFS

2.  Open QGIS

    1.  Zet project CRS op EPSG:28992
    2.  Kies 'Kaartlagen' $\rightarrow$ 'Databronnen beheren' $\rightarrow$ 'WFS / OGC API - Objecten'

3.  Klik 'Nieuw' bovenaan in het dialoogvenster om een nieuwe WFS-verbinding te maken

    1.  Gebruik als 'naam' `sovon` en als 'url' `https://portal.sovon.nl/views/wfs/453/`
    2.  Klik op 'OK'

4.  Maak een verbinding met de zopas toegevoegde WFS

    1.  Klik op 'Verbinden' bovenaan in het dialoogvenster
    2.  Geef je gebruikersnaam en paswoord in wanneer dit wordt gevraagd en klik op 'OK'
    3.  Selecteer de laag 'ms:viewpoints'
        -   Maak eventueel een specifieke SQL-query aan via 'Query maken' onderaan in het dialoogvenster
        -   Bijvoorbeeld voor de data 2024: `SELECT * FROM viewpoints WHERE jaar = 2024`
    4.  Vink het boxje aan 'Alleen objecten bevragen die het huidige zichtbare bereik overlappen'
    5.  Wijzig het Coördinaten Referentiesysteem naar EPSG:28992
    6.  Klik op 'Toevoegen' onderaan in het dialoogvenster
        -   Indien QGIS vraagt de toe te voegen items te selecteren, selecteer je de laag 'ms:viewpoints' en klik je op 'Lagen toevoegen'

Nu worden alle data waar je toegang toe hebt gedownload (dit kan even duren).
Dit zijn de waarnemingen van de MAS-tellingen in Vlaanderen.

## Exporteren en lokalisatie van de data

Wanneer alle data gedownload zijn, kan je deze laag exporteren.
Verdere opschoning en preparatie van de data gebeuren in de code repository "mbag-mas" [@github-repo-mas].
De volgende stappen beschrijven dan ook de lokalisatie van de data binnen deze repository.

1.  Zorg dat alle data zichtbaar zijn in de view van QGIS

2.  Selecteer 'Kaartlagen' $\rightarrow$ 'Opslaan als ...'

    -   Gebruik als 'Indeling' `GeoJSON`
    -   Gebruik als 'Bestandsnaam' `YYYYMMDD_qgis_export_sovon_wfs_JAAR`
        -   `YYYYMMDD` is de datum van export
        -   `JAAR` is het jaar wanneer de data verzameld is (zie SQL-query)
        -   Sla het geojson-bestand op in de folder `mbag-mas/data/mas`.
    -   Gebruik als 'CRS' `EPSG:28992 - Amersfoort / RD New`
    -   Klik op 'OK' (dit kan even duren)

3.  De finale export die je wilt gebruiken voor data preparatie en verdere analyses, sla je op in een folder met als naam `JAAR` onder `mbag-mas/source/targets/data_preparation/data`.
    Elke folder mag slechts 1 bestand hebben met de data van dat jaar.

```{=html}
<!--
Geef hier een overzicht van de stappen van het project protocol.
De verschillende stappen moeten verduidelijkt worden met criteria en richtlijnen wanneer wat moet uitgevoerd worden.
Bijvoorbeeld:
Ga naar de te monitoren locatie.
Volg subprotocol A `<protocol-code>_YYYY.NN` om te bepalen of de locatie tot de doelpopulatie die men wil monitoren behoort (eerste bezoek) of nog steeds behoort (herhaald bezoek).
Volg subprotocol B `<protocol-code>_YYYY.NN` waarin de staalnameprocedure wordt uitgelegd.
Volg subprotocol C `<protocol-code>_YYYY.NN` waarin labo-analyse wordt uitgelegd.

De doelstelling is om de subprotocols te organiseren in een coherent hoofd protocol waarin ontbrekende elementen aangevuld worden die niet in de subprotocols staan, zoals wanneer een bepaald subprotocol wel of niet wordt uitgevoerd, of kleine extra stappen die geen eigen subprotocol vereisen.
-->
```
