# Kwaliteitszorg

```{=html}
<!--
Vermeld alle acties bij het uitvoeren van het protocol om tot kwaliteitsvolle resultaten te komen.
Daarnaast kan ook een checklist toegevoegd worden om na te gaan of alle stappen van het veldprotocol op een correcte manier doorlopen zijn (bv. Zijn alle velden in veldformulier ingevuld, zijn alle stalen gelabeld, ...).
Indien er niet aan bepaalde kwaliteitscriteria voldaan wordt, kan er eventueel verwezen worden naar corrigerende maatregelen.
In dit onderdeel kunnen ook bepaalde interkalibratie-oefeningen vermeld worden, die bijvoorbeeld voorafgaand aan elk veldseizoen worden uitgevoerd door de gebruikers van het protocol. 
-->
```
Zie kwaliteitszorg van protocol [sfp-113 2023.04](../2023.04/index.html).

Neem steeds alle relevante protocollen mee in het veld en kijk voor het vertrek steeds na of al het materiaal aanwezig is en of op batterijen werkende toestellen voldoende zijn opgeladen.
De checklist van het veldmateriaal staat in Tabel \@ref(tab:Tabel1).

Specimens die op het terrein niet op naam kunnen worden gebracht, worden meegenomen naar het labo ter identificatie; bij twijfel wordt dit specimen voorgelegd aan derden ter controle.

Voor elke in Recorder ingevoerde opname wordt gecontroleerd of het aantal ingevoerde soorten overeenkomt met het aantal op het veldformulier.

Nadat alle metingen van een veldseizoen zijn geregistreerd in Recorder, wordt een kwaliteitscontrole uitgevoerd met behulp van een R-script (kwaliteitscontrole_datainvoer.Rmd; download [hier](https://drive.google.com/file/d/1ytxdQIP0Lbw7cXASoeXTHmfMsKXoqk5z)).
