# Veiligheid

```{=html}
<!--
Alle aandachtspunten in verband met veilig werken.
-->
```
Tijdens het veldwerk gelden volgende veiligheidsregels:

-   algemene veiligheidsregels voor het werken in en nabij water (sfp-112; protocol te ontwikkelen);

-   bioveiligheidsmaatregelen voor het voorkomen van de verspreiding van invasieve exoten (sfp-015; protocol te ontwikkelen).

Voorzichtigheid is ten zeerste geboden bij diepe en snelstromende waterlopen, bij weke waterbodem en bij gladde taluds.
Gebruik een veiligheidstouw of reddingsvest wanneer de situatie dit vereist.
Bij vegetatieopname vanop een boot dient deze volledig in orde te zijn en worden te allen tijde zwemvesten gedragen door alle opzittenden.

Neem een hark of stevige stok mee als steun bij het doorwaden van de waterloop of plas wanneer de situatie dit vereist.
Deze kan gebruikt worden om de waterdiepte te peilen, om je evenwicht te behouden of om een steile oever te beklimmen.

Tijdens een vegetatieopname in water draagt men waterdichte handschoenen; na de opname wast men de handen met ontsmettende, fosfaatvrije zeep om het risico op besmetting te beperken.

De veldmedewerker beschikt steeds over een GSM en een lijst van nuttige telefoonnummers.
