# Samenvatting

```{=html}
<!-- 
Een samenvattende opsomming van de te volgen stappen.
Gebruik eventueel een stroomschema indien dit het protocol kan verduidelijken.
-->
```
## Methoderecept

-   Baken het proefvlak af en verdeel het in `r params$aantal_steken` rastercellen

-   Neem eerst van elke rastercel een monster kloksgewijs (in wijzerzin), eindig met het centrale monster

-   Verwijder bij elk monsters het overtollig materiaal van de guts

-   Neem van elk monster het gewenste materiaal (in dit geval van `r params$begin_diepte_cm` -- `r params$eind_diepte_cm` cm diep) en breng in een mengemmertje

-   Verwijder zoveel mogelijk het materiaal dat niet mee opgenomen mag worden in het laboratoriummonster (levend materiaal, steentjes, ...)

-   Homogeniseer het mengmonster in een mengemmertje en breng over in een monsterbakje

-   Etiketteer het mengmonster

-   Vul het opnameformulier in (voorbeeld in bijlage \@ref(bijlage-opnameformulier))

-   Sluit de boorgaten af met overtollig monster

-   Bewaar het mengmonster
