---
title: Bemonsteren aan de hand van oppervlaktemonsters
subtitle: Manueel met steekguts
author:
  - name: Nathalie Cools
    orcid: 0000-0002-7059-2318
  - name: Bruno De Vos
    orcid: 0000-0001-9523-3453
date: 2021-05-12
reviewers: [Hans Van Calster]
file_manager: Hans Van Calster
protocol_code: sfp-201-nl
version_number: "2023.02"
language: nl
lang: nl
theme: soil
site: bookdown::bookdown_site
template_name: sfp
bibliography: referenties.yaml
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
params:
  proefvlak_vorm: "vierkant"
  begin_diepte_cm: 0
  eind_diepte_cm: 10
  aantal_steken: !r 3^2
  guts_diameter_mm: 25
---

```{=html}
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titels staan en vermeld expliciet "niet van toepassing".
-->
```
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
library(ggplot2)
library(pander)
panderOptions("table.alignment.default", "left")
metadata <- rmarkdown::metadata
path_to_protocol <- get_path_to_protocol(metadata$protocol_code)
type <- get_protocol_type(metadata$protocol_code, auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
tibble(
  reviewers = metadata[["reviewers"]] |> paste(collapse = ", "),
  documentbeheerder = metadata[["file_manager"]],
  protocolcode = metadata[["protocol_code"]],
  versienummer = metadata[["version_number"]],
  taal = metadata[["language"]],
  thema = metadata[["theme"]]
) %>%
  pander::pander(split.tables = Inf)
```

```{r results="asis"}
sprintf("Controleer [deze tabel](../%s.html){target=\"_blank\"} om te zien of een meer recente versie beschikbaar is.", type) |> cat() # nolint
```
