---
title: Richtlijnen voor het bepalen van het waterpeil in peilbuizen
author:
- name: Toon Van Daele
  orcid: 0000-0002-1362-853X
- name: Piet De Becker
  orcid: 0000-0002-9686-0472
- name: Mathias Wackenier
  orcid: 0000-0001-6934-9241
date: '`r Sys.Date()`'
reviewers: Gerrit Genouw
file_manager: Mathias Wackenier
protocol_code: sfp-106-nl
version_number: '2023.02'
language: nl
lang: nl
theme: water
site: bookdown::bookdown_site
template_name: sfp
bibliography:
- referenties.yaml
- referenties.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
params:
  dependencies:
    value:
    - protocol_code: sfp-104-nl
      version_number: '2023.03'
      params: .na
      appendix: false
---

```{=html}
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titels staan en vermeld expliciet "niet van toepassing".
-->
```
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
library(pander)
panderOptions("table.alignment.default", "left")
metadata <- rmarkdown::metadata
path_to_protocol <- get_path_to_protocol(metadata$protocol_code)
type <- get_protocol_type(metadata$protocol_code, auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
tibble(
  reviewers = metadata[["reviewers"]] |> paste(collapse = ", "),
  documentbeheerder = metadata[["file_manager"]],
  protocolcode = metadata[["protocol_code"]],
  versienummer = metadata[["version_number"]],
  taal = metadata[["language"]],
  thema = metadata[["theme"]]
) %>%
  pander::pander(split.tables = Inf)
```

```{r results="asis"}
sprintf("Controleer [deze tabel](../%s.html){target=\"_blank\"} om te zien of een meer recente versie beschikbaar is.", type) |> cat() # nolint
```
