---
output:
  pdf_document: default
  html_document: default
---

# Overkoepelende werkwijze met verwijzing naar subprotocols

```{=html}
<!--
Geef hier een overzicht van de stappen van het project protocol.
De verschillende stappen moeten verduidelijkt worden met criteria en richtlijnen wanneer wat moet uitgevoerd worden.
Bijvoorbeeld:
Ga naar de te monitoren locatie.
Volg subprotocol A `<protocol-code>_YYYY.NN` om te bepalen of de locatie tot de doelpopulatie die men wil monitoren behoort (eerste bezoek) of nog steeds behoort (herhaald bezoek).
Volg subprotocol B `<protocol-code>_YYYY.NN` waarin de staalnameprocedure wordt uitgelegd.
Volg subprotocol C `<protocol-code>_YYYY.NN` waarin labo-analyse wordt uitgelegd.

De doelstelling is om de subprotocols te organiseren in een coherent hoofd protocol waarin ontbrekende elementen aangevuld worden die niet in de subprotocols staan, zoals wanneer een bepaald subprotocol wel of niet wordt uitgevoerd, of kleine extra stappen die geen eigen subprotocol vereisen.
-->
```

De steekproefeenheden waar een peilbuis-piëzometerkoppel dient te worden geïnstalleerd, worden aangeleverd na de locatie-evaluatie en worden beschikbaar gesteld via een beveiligde server of andere route.
Via een GIS-applicatie (vb. QGIS en QField) worden ze gevisualiseerd aangeboden voor de communicatie van gegevens voor de organisatie op terrein (*outbound*) en de op terrein verzamelde gegegevens (*inbound*).

## Voorbereiding van het bezoek aan de steekproefeenheid

Controleer in de GIS-applicatie wie de eigenaar en/of beheerder is van het gebied waarin de steekproefeenheid gelegen is.

Controleer de toestand van de piëzometers die binnen een straal van 50m van het middelpunt van de steekproefeenheid liggen: - noteer de eigenaar van de piëzometer - controleer of de piëzometer binnen hetzelfde doeltype ligt als de steekproefeenheid op basis van de habitatkaart - controleer of de piëzometer binnen hetzelfde bodemtype ligt als de steekproefeenheid op basis van de bodemkaart.
Indien de steekproefeenheid uit een zwaar bodemtype (A,U, E) bestaat, moet de piëzometer zich binnen de steekproefeenheid bevinden om in aanmerking te komen voor hergebruik.

Controleer of de piëzometer voldoet aan volgende voorwaarden: - de buis heeft een filterlengte van 40-60 cm - de buis heeft een diameter van 5cm - de buis bestaat uit Kiwa-gecertificeerd PVC - de buis valt niet droog (bekijk de tijdsreeksen) noteer of de meetstaat van de bodem is beschreven.

Als de piëzometer voldoet aan de voorwaarden, toets dan af bij de eigenaar of de piëzometer voor de PAS-effectmonitoring gebruikt mag worden.Installeer bijkomend een peilbuis.

Als de piëzometer niet voldoet, toets dan af bij de eigenaar of het punt vervangen mag worden, of vraag aan de terreinbeheerder of de plaatsing mag plaatsvinden op de oorspronkelijk voorziene locatie binnen de steekproefeenheid volgens protocol.
Volg hiervoor de stappen van paragraaf "Bezoek de steekproefeenheid".

Toets af bij de meetnetverantwoordelijke of projectcoördinator of: - vergunningen of toelatingen voorzien zijn; - je bezoek en de plaatsing van de peilbuis en piëzometer is gemeld bij de eigenaar en/of beheerder (vb. privé-eigenaars en openbare besturen, boswachters en regiobeheerders van ANB, consulenten en conservators van Natuurpunt, Limburgs Landschap, vzw Durme, ...); - er tijdelijke beperking is van toegang (vb. tijdens het broedseizoen) - een controle in het [KLIP-portaal](https://klip.vlaanderen.be/public) noodzakelijk en uitgevoerd is, om graafschade te voorkomen aan kabels en leidingen.

Kondig je terreinbezoek minstens twee dagen op voorhand aan bij de terreinbeheerder.
Toegankelijkheid van militaire gebieden dient een week voor het terreinbezoek aangevraagd te worden via mail aan het betreffende kwartier, met de boswachter in cc.
Zij laten weten op welke dagen en tussen welke uren je het terrein mag betreden.
Bij het betreden en het verlaten van het terrein op de dag zelf dien je telkens telefonisch contact op te nemen met de kwartiercommandant.

## Bezoek de steekproefeenheid

Ga naar de volgende paragraaf als een bestaand meetpunt wordt hergebruikt.

Navigeer naar de steekproefeenheid met behulp van een RTK-GPS-ontvanger of de GPS-ontvanger van je tablet of smartphone.
In terrestrische steekproefeenheden is het celmidden aangeduid met markeeranker en meetmerk (en eventueel met bamboestok), waardoor een GPS-ontvanger in je tablet of smartphone voldoende zal zijn om het celmidden terug te vinden.
Als je het markeeranker met meetmerk toch niet terugvindt, dien je een RTK-GPS-ontvanger te gebruiken en moet je misschien later terugkomen.
Geef dit aan in de GIS-applicatie.

Het terugvinden van aquatische steekproefeenheden vereist sowieso geen nauwkeurige locatiebepaling; een GPS-ontvanger zal daar volstaan.
Het vinden van een reeds geselecteerd staalnamepunt van een aquatisch type (zie [protocol spp-116-nl 2024.05](https://inbo.github.io/protocols/2024.05/index.html) en [protocol spp-117-nl 2024.06](https://inbo.github.io/protocols/2024.06/index.html) vereist wel het gebruik van een RTK-GPS-ontvanger.

### Koppeling met bestaande MNM-meetpunten

Koppeling met reeds bestaande random MNM-locaties is mogelijk indien aan onderstaande voorwaarden wordt voldaan:

- de cellen raken elkaar, inclusief de cellen die diagonaal raken via de hoekpunten. De celkateringspolygonen hoeven elkaar niet te raken.
- de cellen vertegenwoordigen hetzelfde habitattype.

## Positionering en evaluatie van installatiepunt(en)

Afhankelijk van het doeltype beschik je over een bepaalde set van random punten waar het doeltype aanwezig is en waar peilbuis en piëzometer kunnen geïnstalleeerd worden.
Deze zijn via desktop-analyse of analyse ter plaatse reeds gegenereerd:

- terrestrische types: binnen het celkarteringspolygoon in celmiddengebaseerde types of waar het type gedetecteerd is in celgebaseerde types (habitattypes 1320, 2150, 6210_sk, 6430_bz en 7150 en de rbb-types brem- en gaspeldoornstruweel (rbbsg) en doornstruweel (rbbsp)), met uitsparing van het permanente kwadraat (3 m op 3 m; in bossen 10 m op 10 m) voor de monitoring van de biotische habitatkwaliteit en buffer van 1 m errond;

- aquatische types:

  - stilstaande wateren: in 50 m brede zone rond de plas, beperkt tot een gebied van 30 graden rond de richting van de sterkste helling (bepaald over een range van 500 m);
  - stromende wateren (habitattype 3260): in een zone tussen de 20 en 50 m van de middellijn van de stroom, beperkt door de loodlijnen op de segmenteindes, en aan de kant met de grootste helling

- type 7220: in een 20-m-brede zone van de grootste helling, net buiten het habitat (tot 100 m van de habitatvlek hellingopwaarts en tot 10 m van de habitatvlek hellingafwaarts), om betreding van de gevoelige vegetatie te voorkomen.

De lijst met random punten per steekproefeenheid is beschikbaar in de GIS-applicatie.
De random plaatsingspuntjes zijn toevallig gekozen, maar met een grotere kans voor punten dichter bij het celmidden.
Open de lijst en loop de punten in de lijst systematisch in volgorde af.
Werk hierbij van een laag naar hoog volgnummer.
Evalueer of het eerstvolgende installatiepunt voldoet aan de volgende criteria:

- voldoende grote oppervlakte van de habitatvlek: de habitatvlek van het doeltype moet minstens 9 m² groot zijn zodat bij het plaatsen van de peilbuis en piëzometer niet de ganse habitatvlek verstoort;
- er is geen hinder van obstakels op het punt (bvb. een omgevallen boom)

**Let op**: wanneer je een plaats zoekt om een peilbuis of piëzometer te plaatsen, heb je misschien de neiging om het punt voorzien voor installatie te verplaatsen in functie van beheer (vb. hinder bij maaien of ruimen, op een uitsleeppiste,...), de bereikbaarheid, de zichtbaarheid of persoonlijke voorkeur van de eigenaar of beheerder.Dit tast echter de ruimtelijke representativiteit van het meetpunt aan.De verzamelde data zijn dan mogelijks niet meer representatief voor de milieuvariabelen van de werkelijke standplaats, waardoor er een systematische vertekening (bias) in de monitoring ontstaat.

Het is mogelijk dat de laag met random punten (tijdelijk) onbeschikbaar is.
Contacteer in dit geval de data scientist om de locaties alsnog te verkrijgen.
Indien de data scientist niet bereikbaar is, genereer dan random nummers aan de hand van je smartphone of tablet.

## Conditioneel: gebruik van bestaande meetlocaties

Navigeer naar het bestaande meetpunt met behulp van een RTK-GPS-ontvanger of de GPS-ontvanger van je tablet of smartphone.
Controleer of het meetpunt nog voldoet aan de criteria zoals beschreven in voorgaand hoofdstuk.
Plaats een peilbuis nabij het punt als het punt voldoet.
Als het punt niet voldoet, toets dan af bij de terreinbeheerder of het punt vervangen mag worden, of de plaatsing mag plaatsvinden in de steekproefeenheid volgens protocol.
Volg hiervoor de stappen van paragraaf "Bezoek de steekproefeenheid".

## Plaatsen en geografisch inmeten van piëzometer en peilbuis

Voor het plaatsen van de peilbuis en de piëzometer volg je het protocol 'Richtlijnen voor het plaatsen van peilbuizen' [sfp-104-nl 2025.01](https://inbo.github.io/protocols/2025.01/index.html).

Volg hierbij, in het kader van het meetnet eutrofiëring via het grondwater van de MNM, de volgende projectspecifieke richtlijnen die een (lichte) afwijking of een verfijning zijn van het bovenstaand protocol:

### Diepte van de boring

Controleer de grondwaterafhankelijkheid van het type in de rastercel in onderstaande tabel.
Kolommen 1-3 betreffen terrestrische types met verschillende grondwaterafhankelijkheden (GD2, GD1, GD0), kolom 4 aquatische types (enkel GD2).

| type (ter.) | afh. | type (ter.) | afh. | type (ter.) | afh. | type (aq.) | afh. |
|-------------|------|-------------|------|-------------|------|------------|------|
| 1310_pol    | GD2  | 3260        | GD1  | 6510_hu     | GD0  | 3110       | GD2  |
| 1330_hpr    | GD2  | 9130_end    | GD1  | 9120        | GD0  | 3130_aom   | GD2  |
| 2190_a      | GD2  | 9130_fm     | GD1  |             |      | 3130_na    | GD2  |
| 2190_mp     | GD2  | 9160        | GD1  |             |      | 3140       | GD2  |
| 2190_overig | GD2  | 9190        | GD1  |             |      | 3150       | GD2  |
| 4010        | GD2  |             |      |             |      | 3160       | GD2  |
| 6230_hmo    | GD2  |             |      |             |      | 7220       | GD2  |
| 4010        | GD2  |             |      |             |      |            |      |
| 6230_hmo    | GD2  |             |      |             |      |            |      |
| 6410_mo     | GD2  |             |      |             |      |            |      |
| 6410_ve     | GD2  |             |      |             |      |            |      |
| 6430_hf     | GD2  |             |      |             |      |            |      |
| 6430_hw     | GD2  |             |      |             |      |            |      |
| 6430_mr     | GD2  |             |      |             |      |            |      |
| 6510_hua    | GD2  |             |      |             |      |            |      |
| 6510_hus    | GD2  |             |      |             |      |            |      |
| 7140_base   | GD2  |             |      |             |      |            |      |
| 7140_meso   | GD2  |             |      |             |      |            |      |
| 7140_mrd    | GD2  |             |      |             |      |            |      |
| 7140_oli    | GD2  |             |      |             |      |            |      |
| 7150        | GD2  |             |      |             |      |            |      |
| 7210        | GD2  |             |      |             |      |            |      |
| 7230        | GD2  |             |      |             |      |            |      |
| 91E0_sf     | GD2  |             |      |             |      |            |      |
| 91E0_va     | GD2  |             |      |             |      |            |      |
| 91E0_vc     | GD2  |             |      |             |      |            |      |
| 91E0_vm     | GD2  |             |      |             |      |            |      |
| 91E0_vn     | GD2  |             |      |             |      |            |      |
| 91E0_vo     | GD2  |             |      |             |      |            |      |

**Is het type terrestrisch en behoort het tot GD2?**

Dit type is grondwaterafhankelijk op (bijna) alle locaties.
Initieel wordt hier maximaal 3,5 m diep geboord:

- kom je de reductiehorizont tegen in die bovenste 3,5 m, boor dan tot 1 m onder de bovenkant van de reductiehorizont (de maximale diepte van de onderkant van de peilbuis en piëzometer is dus 4,5 m);
- als je de reductiehorizont niet herkent of tegenkomt in die bovenste 3,5 m en je komt al grondwater tegen, boor dan tot 1 m onder de huidige grondwaterstand (de maximale diepte van de onderkant van de peilbuis en piëzometer is dus 4,5 m);
- kom je geen van beide tegen tot op 3,5 m diepte, neem dan contact op met de meetnetverantwoordelijke.

Noteer in de GIS-applicatie op welke diepte de onderkant van de peilbuis en piëzometer is geplaatst en op basis van welk criterium (reductiehorizont of grondwater) of geef aan dat er geen peilbuis of piëzometer is geplaatst.

**Is het type terrestrisch en behoort het tot GD1 of GD0?**

Dit betreft een terrestrisch type dat grondwaterafhankelijk op een deel van de locaties is (GD1) of niet grondwaterafhankelijk is (GD0).
Initieel wordt hier maximaal 2,5 m diep geboord:

- kom je de reductiehorizont tegen in die bovenste 2,5 m, boor dan tot 1 m onder de bovenkant van de reductiehorizont (de maximale diepte van de onderkant van de peilbuis en piëzometer is dus 3,5 m);
- als je de reductiehorizont niet herkent of tegenkomt in de bovenste 2,5 m en je komt al grondwater tegen, boor dan tot 1 m onder de huidige grondwaterstand (de maximale diepte van de onderkant van de peilbuis en piëzometer is dus 3,5 m);
- kom je geen van beide tegen tot op 2,5 m diepte, dan wordt de installatie gestaakt. Neem bij twijfel contact op met de meetnetverantwoordelijke.

Noteer in de GIS-applicatie op welke diepte de onderkant van de peilbuis en piëzometer is geplaatst en op basis van welk criterium (reductiehorizont of grondwater) of geef aan dat er geen peilbuis of piëzometer is geplaatst.

**Is het type aquatisch en GD2?**

Dit betreft een aquatisch type dat grondwaterafhankelijk is op (bijna) alle locaties (GD2).
De boordiepte is hier variabel en gerelateerd aan het oppervlaktewaterpeil van de steekproefeenheid.

- Meet het waterpeil van de nabijgelegen steekproefeenheid op met RTK-GPS.

- Bepaal de maaiveldhoogte met RTK-GPS op de random locatie en bereken het verschil met het waterpeil van de steekproefeenheid.
  Tel bij dit verschil een buffer van 0,5 m en je bekomt de initiële boordiepte.Bv.
  Het waterpeil van de steekproefeenheid bedraagd 20 m TAW, het maaiveld van random locatie 1 bedraagd 20,70 m TAW.
  De initiële boordiepte bedraagt dan 20,70 m - 20 m + 0,5 m = 1,2 m.

- Boor vervolgens tot deze diepte.
  Kom je de reductiehorizont tegen, boor dan tot 1 m onder de bovenkant van de reductiehorizont.

- als je de reductiehorizont niet herkent of tegenkomt boven de initiële boordiepte en je komt al grondwater tegen, boor dan tot 1 m onder de huidige grondwaterstand.

-Indien er geen grondwater voorkomt binnen de initiële boordiepte wijst dit op een op hydrologisch geïsoleerde plas met geen of maar heel beperkte grondwaterinvloed.
In dit geval wordt de installatie gestaakt.

Noteer in de GIS-applicatie op welke diepte de onderkant van de peilbuis en piëzometer is geplaatst en op basis van welk criterium (reductiehorizont of grondwater) of geef aan dat er geen peilbuis of piëzometer is geplaatst.

**Aanwezigheid van ondiepe kleilenzen**

Deze situatie kan zich voordoen in infiltratiegebieden, vaak met aanwezigheid van vennen, in zandige regio's.
Bij aanwezigheid van ondiepe kleilenzen in de gereduceerde of waterverzadigde zone mag afgeweken worden van de 1 m-regel onder de reductiehorizont.
We willen immers voorkomen dat de kleilens doorboord wordt en er verticale drainage optreedt.
Het geperforeerde deel van zowel peilbuis als piëzometer mag de watervoerende lagen onder en boven de kleilens niet met elkaar verbinden.
Hier worden de buizen op de kleilens geplaatst.
Bij eventuele doorboring wordt de ondoorlaatbaarheid van de laag hersteld aan de hand van een bentonietstop.

**Drooggevallen reductiehorizont**

Indien het een extreem verdroogde locatie betreft (grondwater komt niet voor 1m onder de reductiehorizont) dan wordt de plaatsing gestaakt.

### Plaatsing en naamgeving van de buizen

Plaats de peilbuizen en piëzometers in overeenstemming met protocol sfp-104-nl.
Hou hierbij rekening met volgende afwijkingen:

- Gebruik steeds KIWA-gecertififieerde (BRL-651) blinde buizen en filters uit PV;
- De filterlengte bedraagt 0,6 m;
- plaats per steekproefeenheid telkens één piëzometer en één peilbuis, tot dezelfde diepte;
- plaats steeds een metalen beschermkoker over de piëzometer

Geef bij voorkeur de verzamelde gegevens digitaal in, in Watina of via de GIS-applicatie (vb. boorverslag) en gebruik papieren veldnotities enkel als het digitaal niet kan (vb. te veel neerslag, te koud).

Geef de buizen een watinacode conform protocol sfp-104-nl.
Bepaal eerst het volgnummer van de piëzometer op basis van de beschikbaarheid in Watina.
Voor de peilbuis gebruik je een volgnummer dat 100 volgnummers hoger ligt dan de piëzometer (Vb. ZWAP101 en ZWAP001).
Gebruik geen volgnummers die eindigen op "0" (Vb. ZWAP100 en ZWAP200).

Noteer de watinacode aan de binnenzijde of op de beschermkap van de beschermkoker, vermeld hierbij de versienummer, beginnende bij X, vb.
ZWAP101X).

Plaats op terreinen in maaibeheer of met een hoge, dichte vegetatie een hoge kastanjepaal met oranje markering om de locatie makkelijk terug te vinden en/of ter preventie van maaischade Plaats bijkomende bescherming op steekproefeenheden met begrazingbeheer; dit kan d.m.v. omheining of omplanking.Toets het gebruik van prikkeldraad af met de terreinbeheerder.

## Plaatsen van automatische druksensor

In elke piëzometer plaats je een druksensor.
Een druksensor meet een druk die het resultaat is van de hoogte van de waterkolom boven de sensor en de atmosferische druk.
Een druk van 1 millibar luchtdruk komt overeen met de druk van 1 cm waterkolom.
De atmosferische druk wordt gecompenseerd met barometermetingen.
Wanneer het peil onder de sensor zakt meet de sensor enkel nog de atmosferische druk.

Neem een druksensor (vb. Troll 100) en selecteer uit de lijst het serienummer van de sensor voor die steekproefeenheid in de GIS-applicatie.
Programmeer de druksensor via de software op de veldtablet, met behulp van een Bluetooth-verbinding of rechtstreekse connectie.
Stel de meetfrequentie in (uurlijks) en controleer de vrije opslagruimte en batterij van de druksensor of die kan functioneren bij de gekozen instellingen gedurende de volgende zes maanden.

Maak de druksensor vast aan het uiteinde van de rol kabel met behulp van de kabelklemmen.
Laat de sensor met de kabel in de piëzometer zakken, tot onder de laagst mogelijke grondwaterstand maar 10 cm boven de bodem van de peilbuis waar water met slib kan blijven staan zelfs wanneer het grondwaterpeil onder de piëzometer zakt.
Markeer de hoogte van de bovenkant van de piëzometer op de kabel en haal de sensor weer uit de piëzometer.
Een vijftal cm voorbij de markering knip je de kabel door met de kniptang.
Bevestig het uiteinde van de afgeknipte kabel aan de onderzijde van het peilbuisslot en controleer of de druksensor goed bevestigd is.
Plaats de druksensor aan de draad in de piëzometer.
Plaats het peilbuisslot in de opening van de buis en draai de vijs op het slot vast.
Voer een geografisch inmeting uit via RTK-GPS ontvanger, protocol SVP-014.
Indien geen RTK-GPS ontvanger beschikbaar is, dien je dit binnen de 3 maanden in te halen.
Geografische inmetingen in bos mogen uitgesteld worden naar de winterperiode.

## Geografisch inmeten van peilbuis en piëzometer

Als geen RTK-GPS-ontvanger beschikbaar was bij het plaatsen van de peilbuis en piëzometer, dien je later (bij voorkeur binnen de 3 maanden) met de RTK-GPS-ontvanger terug te komen om de geografische locatie (x,y,z) ervan nauwkeurig in te meten.
Volg hiervoor [protocol SVP-014](https://docs.google.com/document/d/1T68iO3-gZ9WrUTxEd551n5EXPrp0vNp9bPs-Y_xSP-U/edit?tab=t.0).

## Terrestrische types en 7220: inmeten van gemiddelde maaiveldhoogte

In het geval van steekproefeenheden van terrestrische types en type 7220 dient de gemiddelde maaiveldhoogte bepaald te worden.
Dit kan onmiddellijk na de plaatsing van de peilbuis en piëzometer maar kan ook op een later tijdstip.
Om de lokale ruimtelijke variatie in maaiveldhoogte mee in rekening te brengen, wordt de maaiveldhoogte bepaald op meerdere locaties binnen de celkarteringspolygoon.
Met de RTK-GPS-ontvanger bepaal je de maaiveldhoogte op twintig random punten in de celkarteringspolygoon.
Deze punten worden ter beschikking gesteld in de GIS-applicatie.
Je volgt hierbij de toegekende rangorde van de punten.
Bij de overname van een bestaande buis buiten het celkarteringspolygoon wordt nog steeds het oorspronkelijke celkarteringspolygoon opgemeten.

## Aquatische types: plaatsen en geografisch inmeten van peilschaal

In het geval van aquatische types (lentisch en lotisch), plaats je ook een peilschaal.
De verklarende variabele voor stikstoftoestand in het grondwater is hier namelijk het verschil tussen grondwaterpeil en oppervlaktewaterpeil.
Volg hiervoor [protocol SVP-119](https://drive.google.com/file/d/129ch-zbjzQi3BkX0wRm0KSrM6fvwlwH8/view).
Als een RTK-GPS-ontvanger mee op het terreinbezoek is gebracht, kan onmiddellijk na plaatsing van de peilschaal de geografische locatie (x,y,z) ervan nauwkeurig worden bepaald.
Als geen RTK-GPS-ontvanger beschikbaar was bij het plaatsen van de peilschaal, dien je later (bij voorkeur binnen de 3 maanden) met de RTK-GPS-ontvanger terug te komen om de geografische locatie (x,y,z) ervan nauwkeurig in te meten.

## Controle

Controleer na één maand de werking van de peilbuis en piëzometer.
Controleer of de peilbuis en piëzometer voldoende water aanvoeren door ze leeg te pompen en het hervullen op te volgen.
Vanaf anderhalve maand na installatie en na controle kunnen ze gebruikt worden voor staalname.
De controle en het leegpompen voor de staalname kunnen dus samen uitgevoerd worden.
