---
title: "Plaatsen van een peilbuis-piëzometer in steekproefeenheden van het meetnet
  eutrofiëring via het grondwater (GW_03.3) van de Meetnetten Natuurlijk Milieu"
author:
- name:
    given: Karen
    family: Wuyts
  email: karen.wuyts@inbo.be
  orcid: "0000-0002-3371-6828"
  affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  corresponding: true
- name:
    given: Tom
    family: De Dobbelaer
  email: tom.dedobbelaer@inbo.be
  orcid: "0000-0001-7636-997X"
  affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
- name:
    given: Falk
    family: Mielke
  email: falk.mielke@inbo.be
  orcid: "0000-0003-3229-0981"
  affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
keywords: mnm; grondwater; eutrofiëring; peilbuis; piëzometer
language: nl
lang: "nl-BE"
reviewer:
- name:
    given: Mathias
    family: Wackenier
  email: mathias.wackenier@inbo.be
  orcid: "0000-0001-6934-9241"
  affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
protocol_code: "spp-003-nl"
version_number: '2026.02'
template_name: spp
project_name: mnm
community: inbo
publisher: "Instituut voor Natuur- en Bosonderzoek (INBO)"
rightsholder:
- name:
    given: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  email: info@inbo.be
  ror: 00j54wy13
funder:
- name:
    given: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  email: info@inbo.be
  ror: 00j54wy13
site: bookdown::bookdown_site
bibliography: referenties.yaml
link-citations: true
license: "CC-BY 4.0"
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl"
params:
  dependencies:
    value:
    - protocol_code: "sfp-104-nl"
      version_number: '2025.01'
      params: null
      appendix: false
file_manager:
- name:
    given: Karen
    family: Wuyts
  email: karen.wuyts@inbo.be
  orcid: "0000-0002-3371-6828"
  affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
---

```{=html}
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titel hoofdingen staan en vermeld expliciet "niet van toepassing".
-->
```

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
library(pander)
panderOptions("table.alignment.default", "left")
metadata <- rmarkdown::metadata
path_to_protocol <- get_path_to_protocol(metadata$protocol_code)
type <- get_protocol_type(metadata$protocol_code, auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
revs <- map_chr(
  metadata[["reviewer"]],
  \(x) x$name |> paste(collapse = " ")
)
fms <-  map_chr(
  metadata[["file_manager"]],
  \(x) x$name |> paste(collapse = " ")
)
tibble(
  reviewers = paste(revs, collapse = ", "),
  documentbeheerder = fms,
  protocolcode = metadata[["protocol_code"]],
  versienummer = metadata[["version_number"]],
  taal = metadata[["language"]],
  projectnaam = metadata[["project_name"]]
) %>%
  pander::pander(split.tables = Inf)
rm(revs, fms)
```

```{r results="asis"}
sprintf("Controleer [deze tabel](../%s.html){target=\"_blank\"} om te zien of een meer recente versie beschikbaar is.", type) |> cat() # nolint
```
